### DISCUSSION TITLE
E! [outputs.influxdb_v2] When writing to [http://127.0.0.1:8181/api/v2/write]: failed to write metric to (will be dropped: 400 Bad Request): :

### DISCUSSION THREAD

**Discussion by dlukt** [influxdata/influxdb#26522] [Q&A] [answered]
Fresh Influx Core 3 installation
```
influxdb3 -V
influxdb3 3.1.0, revision 482dd8aac580c04f37e8713a8fffae89ae8bc264
telegraf version
Telegraf 1.34.4 (git: HEAD@e7ce1e1e)
```

conf
```toml
[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8181"]
  token = "something"
  organization = "icod"
  bucket = "domain.tld"
```

Error
```
E! [outputs.influxdb_v2] When writing to [http://127.0.0.1:8181/api/v2/write]: failed to write metric to (will be dropped: 400 Bad Request): :
```
