### ISSUE TITLE
Prometheus gets HTTP 400 when using the /api/v1/prom/{read,write} endpoints

### ISSUE THREAD

**Issue by coaxial** [influxdata/influxdb#10247]
__System info:__ Ubuntu 18.04, influxdb 1.6.2, Prometheus 2.3.2 20180712-14:02:52 build

__Steps to reproduce:__

1. Configure Prometheus with:
```yaml
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: prometheus

remote_write:
  - url: http://influxdb:8086/api/v1/prom/read?db=prometheus

remote_read:
  - url: http://influxdb:8086/api/v1/prom/write?db=prometheus

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - prometheus:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node
```
2. Use the default influxdb config
3. Watch Prometheus spit out `HTTP status 400 Bad Request: {"error":"proto: wont wireType = 2 for field StartTimestampsMs"}`

__Expected behavior:__

No errors, Prometheus is able to read and write to InfluxDB

__Actual behavior:__

`HTTP status 400 Bad Request: {"error":"proto: wont wireType = 2 for field StartTimestampsMs"}`

__Additional info:__ 

Error: `Aug 30 19:43:36 prometheus prometheus[2109]: level=warn ts=2018-08-30T19:43:36.377701754Z caller=queue_manager.go:530 component=remote queue="0:http://influxdb:8086/api/v1/prom/read?db=prometheus" msg="Error sending samples to remote storage" count=100 err="server returned HTTP status 400 Bad Request: {\"error\":\"proto: wrong wireType = 2 for field StartTimestampMs\"}"`

```
> SHOW DATABASES
name: databases
name
----
prometheus
_internal
> SHOW MEASUREMENTS ON prometheus
> # no records at all
```
