### ISSUE TITLE
Docker pull with Raspberry Pi: "no matching manifest for unknown in the manifest list entries"

### ISSUE THREAD

**Issue by ns-cweber** [influxdata/influxdb#10288]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Raspberry Pi 3B using Raspbian Stretch Lite
Docker version:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:30:52 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:26:37 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

__Steps to reproduce:__

1. `docker pull influxdb:1.6-alpine` OR `helm install stable/influxdb`

__Expected behavior:__ [What you expected to happen]

Image pull succeeds.

__Actual behavior:__ [What actually happened]

Image pull fails with error: `no matching manifest for unknown in the manifest list entries`

This appears to be specific to this tag; `latest` works fine.

**Comment by RezzZ** [comment]
I have exactly the same problem trying to pull mariadb.
```
ERROR: for mariadb  no matching manifest for unknown in the manifest list entries
ERROR: no matching manifest for unknown in the manifest list entries
```

Platform: Raspberry Pi 3B+ running up-to-date version of Rasbian Stretch Lite
running versions:
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
$ docker-compose -v
docker-compose version 1.22.0, build f46880f

My compose file
```
version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYPASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

**Comment by prashu20** [comment]
Same issue even I am facing on my raspberry pi 3b+

**Comment by ns-cweber** [comment]
Any updates on this issue? It's been nearly a year.

**Comment by madzur** [comment]
I am having a similar issue.

When trying to do a docker-compose pull, i get the following error:

```
ERROR: for influxdb  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

My docker compose looks as follows:
```
  influxdb:
    container_name: influxdb
    image: arm32v7/influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - /opt/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /opt/influxdb:/var/lib/influxdb
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
```

In January, I've had success with the following docker compose, however, same error happens now

```
  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - /opt/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /opt/influxdb:/var/lib/influxdb
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
```

Any ideas for how to debug this, please?
