### ISSUE TITLE
InfluxDB 2.0: LabelUpdate schema has to have defined properties as dictionary [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#12545]
The `LabelUpdate` schema has defined `properties` as:

 _Key/Value pairs associated with this label. Keys can be removed by sending an update with an empty value._

but there is missing `additionalProperties` as is specified in [OpenAPI 3 specification for dictionaries](https://swagger.io/docs/specification/data-models/dictionaries/). The `LabelUpdate` schema has to be defined in this way:

```yml
LabelUpdate:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
          description: Key/Value pairs associated with this label. Keys can be removed by sending an update with an empty value.
          example: {"color": "ffb3b3", "description": "this is a description"}
```
