### ISSUE TITLE
InfluxDB 2.0: The SecretKeys response doesn't contains the self link [area/api] 

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#12587]
The `SecretKeys` schema has defined `self` and `org` link:

```yaml
SecretKeys:
      properties:
        links:
          type: object
          properties:
            self:
              type: string
            org:
              type: string
        secrets:
          type: array
          items:
            type: string
```

but the http response contains a `secrets` link instead of a `self`:

```bash
-> GET 
-> http://127.0.0.1:9999/api/v2/orgs/0389792ff6259000/secrets

<- 200 
<- OK
<- {
	"links": {
		"org": "/api/v2/orgs/0389792ff6259000",
		"secrets": "/api/v2/orgs/0389792ff6259000/secrets"
	},
	"secrets": ["az", "gh"]
}
```
