### ISSUE TITLE
InfluxDB 2.0: TelegrafPlugins schemas are too complicated [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#12627]
#### The schemas for `TelegrafPlugin*Request` are defined with multiple inheritance:

```yaml
 TelegrafPluginInputCpuRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/TelegrafRequestPlugin"
        - $ref: "#/components/schemas/TelegrafPluginInputCpu"
```

but the multiple inheritance is not supported in many languages such as TypeScript and Java.

The generated client don't respect the meaning of swagger.yml:

##### TypeScript
```typescript
/**
 * 
 * @export
 * @interface TelegrafPluginInputCpuRequest
 */
export interface TelegrafPluginInputCpuRequest extends TelegrafRequestPlugin {
}
```

##### Java
```java
public class TelegrafPluginInputCpuRequest extends TelegrafRequestPlugin {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TelegrafPluginInputCpuRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
```

#### There is also a conflict between `TelegrafRequestPlugin.name` and a concrete plugin schema declaration:

`TelegrafRequestPlugin.name` is declared as a `string`:
```yaml
TelegrafRequestPlugin:
      type: object
      discriminator:
        propertyName: "name"
      required:
        - name
        - type
      properties:
        name:
          type: string
          example: cpu
        type:
          type: string
          enum:
            - input
            - output
```

but the `TelegrafPluginInputCpuRequest.name` is declared as an enum (through `allOf: TelegrafPluginInputCpu`)  :

```yaml
TelegrafPluginInputCpu:
      type: object
      required:
        - name
        - type
        - config
      properties:
        name:
          type: string
          enum: ["cpu"]
        type:
          type: string
          enum: ["input"]
        comment:
          type: string
        config:
          $ref: "#/components/schemas/TelegrafPluginConfig"

TelegrafPluginInputCpuRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/TelegrafRequestPlugin"
        - $ref: "#/components/schemas/TelegrafPluginInputCpu"
```

----------

I think that there are two solution:

1. Create a custom [openapi-generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md)
1. Or remove inheritance from swagger.yml (Is it even possible?)

Or is there other way how solve these problems?
