### ISSUE TITLE
INFLUXDB_DB not creating the DB - Kubernetes deployment chart

### ISSUE THREAD

**Issue by psmod2** [influxdata/influxdb#12642]
Hi,

I've the following Kubernetes deployment file, I'm using the `INFLUXDB_DB` env variable as described here:
https://hub.docker.com/_/influxdb

however its not actually creating the DB - I have to use curl afterwards which isn't what I want to do:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb/influxdb
          imagePullPolicy: Always
          env:
            - name: INFLUXDB_DB
              value: my_metrics
          ports:
            - containerPort: 8086
```

Any ideas?
