### ISSUE TITLE
Redundant CSS in build output

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#12715]
Our built CSS is including the same rules repeatedly. For example the following rule appears 79 times:

```css
div.faux-form .form-group.col-xs-12 {
  padding-left: 6px;
  padding-right: 6px;
}
```

My guess is that we get duplicated rules every time we import a stylesheet from a component, and that stylesheet imports the `src/styles/modules` stylesheet. A quick search of our codebase shows that we import `src/styles/modules` in 81 files... eerily close to the 79 times that rule is being duplicated.

The result is that our CSS is a whopping 1.1M.
