### ISSUE TITLE
InfluxDB write timeout/freeze

### ISSUE THREAD

**Issue by kMeillet** [influxdata/influxdb#12731]
Hi.

# Reproduction

I'm using InfluxDB v1.6 with Docker For Windows through WSL : my setup is mostly basic (a single "docker-compose.yml" file and a 15 line script to push data)

```
docker-compose up -d
```

```
version: '3'

services:
  influxdb:
    image: influxdb:1.6
    volumes:
      - vol_influx:/var/lib/influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
    - INFLUXDB_DB=testdb
    - INFLUXDB_HTTP_AUTH_ENABLED=false
    - INFLUXDB_ADMIN_USER=root
    - INFLUXDB_ADMIN_PASSWORD=*********
    - INFLUXDB_USER=user
    - INFLUXDB_USER_PASSWORD=********
    - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    - INFLUXDB_COORDINATOR_WRITE_TIMEOUT=60s
    - INFLUXDB_REPORTING_DISABLED=true
  chronograf:
    image: chronograf:1.6
    restart: always
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "8888:8888"
    links:
      - influxdb

volumes:
  vol_influx:
````

Then, i push a small batch with Node Influx library (https://github.com/node-influx/node-influx), with sparse timestamp :

```
const now = Date.now();

const data = [...new Array(20)].map((_, i) => ({
  measurement: 'something',
  timestamp: now + i * 10000, // (add 0s to timestamp, then 10s, then 20s, ...)
  tags: { information: 'ok' },
  fields: {
    speed: 1,
  },
}));

nodeInflux.write(data).then(console.log).catch(console.error);
```

Response -> "Internal Server Error" 

# Docker InfluxDB logs :

```
influxdb_1_5a52b0206eaa | [httpd] 192.168.16.1 - root [19/Mar/2019:15:40:49 +0000] "POST /write?db=testdb&p=%5BREDACTED%5D&precision=n&rp=&u=root HTTP/1.1" 500 20 "-" "-" 5f0d7c4d-4a5d-11e9-8023-000000000000 10000707
influxdb_1_5a52b0206eaa | ts=2019-03-19T15:40:59.865133Z lvl=error msg="[500] - \"timeout\"" log_id=0EHe_brl000 service=httpd
```
