### ISSUE TITLE
InfluxDB 2.0: The Ready schema doesn't have a property "started" [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#12810]
The `/ready` response is defined with the property `start`:

```yaml
Ready:
      type: object
      properties:
        status:
          type: string
          enum:
            - ready
        start:
          type: string
          format: date-time
          example: "2019-03-13T10:09:33.891196-04:00"
        up:
          type: string
          example: "14m45.911966424s"
```

but the HTTP response contains the property `started`:

```bash
-> GET 
-> http://127.0.0.1:9999/ready

<- 200 
<- OK
<- {
    "status": "ready",
    "started": "2019-03-19T12:32:51.70187034Z",
    "up": "5h57m29.252527827s"
}
```
