### ISSUE TITLE
InfluxDB 2.0: MapVariableProperties schema has to have defined "values" as dictionary [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#12948]
The [`VariableMapValues`](https://github.com/influxdata/influxdb/blob/5f524eb92d95a2fcab03f0df23896a2e094dc2d8/variable.go#L107) is defined as:

```go
// VariableMapValues are the data for expanding a map-based Variable
type VariableMapValues map[string]string
```

but in `swagger.yml` is missing `additionalProperties` as is specified in [OpenAPI 3 specification for dictionaries](https://swagger.io/docs/specification/data-models/dictionaries/). 

The `MapVariableProperties` schema should be defined in this way:
```yml
MapVariableProperties:
      properties:
        type:
          type: string
          enum: ["map"]
        values:
          type: object
          additionalProperties:
            type: string
```
