### ISSUE TITLE
InfluxDB 2.0: The "Cell" schema should has defined "name" property [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13079]
The `CreateCell` schema has defined `name` property:

```yaml
CreateCell:
      type: object
      properties:
        name:
          type: string
        x:
          type: integer
          format: int32
        "y": # Quoted to prevent YAML parser from interpreting y as shorthand for true.
          type: integer
          format: int32
        w:
          type: integer
          format: int32
        h:
          type: integer
          format: int32
        viewID:
          type: string
          description: uses the view provided in the request
        usingView:
          type: string
          description: makes a copy of the provided view
```

but the `Cell` hasn't:

```yaml
Cell:
      type: object
      properties:
        id:
          type: string
        links:
          type: object
          properties:
            self:
              type: string
            view:
              type: string
        x:
          type: integer
          format: int32
        "y": # Quoted to prevent YAML parser from interpreting y as shorthand for true.
          type: integer
          format: int32
        w:
          type: integer
          format: int32
        h:
          type: integer
          format: int32
        viewID:
          type: string
          description: The reference to a view from the views API
```

I think the `Cell` should have all properties from `CreateCell`.
