### ISSUE TITLE
InfluxDB 2.0: The "EmptyViewProperties" doesn't have specified  a type to the "empty" [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13084]
The `EmptyViewProperties` schema is defined as:

```yaml
EmptyViewProperties:
      properties:
        type:
          type: string
          enum: ["empty"]
```

but [go implementation](https://github.com/influxdata/influxdb/blob/master/dashboard.go#L308) doesn't have specified a type:

```go
type EmptyViewProperties struct{}

func (v EmptyViewProperties) viewProperties() {}

func (v EmptyViewProperties) GetType() string { return "" }
```
