### ISSUE TITLE
InfluxDB 2.0: The Cell doesn't  contains the "viewId" [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13080]
The `Cell` schema is defined  as:

```yaml
Cell:
      type: object
      properties:
        id:
          type: string
        links:
          type: object
          properties:
            self:
              type: string
            view:
              type: string
        x:
          type: integer
          format: int32
        "y": # Quoted to prevent YAML parser from interpreting y as shorthand for true.
          type: integer
          format: int32
        w:
          type: integer
          format: int32
        h:
          type: integer
          format: int32
        viewID:
          type: string
          description: The reference to a view from the views API
```

but the http response to `GET /dashboards/{dashboardID}` doesn't  contains the `viewId`:

```bash
# Create Dashboard
-> POST 
-> http://127.0.0.1:9999/api/v2/dashboards
-> {"orgID":"039fb4c339500000","name":"dashboard1554200899766-IT","description":"coolest dashboard"}

# Create Cell
-> POST
-> http://127.0.0.1:9999/api/v2/dashboards/03a36545488ec000/cells
-> {"name":"my-cell","x":20,"y":25,"w":15,"h":10}

# Add the view to a cell.
-> PATCH
-> http://127.0.0.1:9999/api/v2/dashboards/03a36545488ec000/cells/03a365455bcec000/view
-> {"name":"view-name","properties":{"type":"markdown","shape":"chronograf-v2","note":"my-note"}}

-> GET
-> http://127.0.0.1:9999/api/v2/dashboards/03a36545488ec000

<- 200 
<- OK
<- {
	"id": "03a36545488ec000",
	"orgID": "039fb4c339500000",
	"name": "dashboard1554200899766-IT",
	"description": "coolest dashboard",
	"meta": {
		"createdAt": "2019-04-02T12:28:19.874461+02:00",
		"updatedAt": "2019-04-02T12:28:19.951822+02:00"
	},
	"cells": [{
		"id": "03a365455bcec000",
		"x": 20,
		"y": 25,
		"w": 15,
		"h": 10,
		"links": {
			"self": "/api/v2/dashboards/03a36545488ec000/cells/03a365455bcec000",
			"view": "/api/v2/dashboards/03a36545488ec000/cells/03a365455bcec000/view"
		}
	}],
	"labels": [],
	"links": {
		"self": "/api/v2/dashboards/03a36545488ec000",
		"members": "/api/v2/dashboards/03a36545488ec000/members",
		"owners": "/api/v2/dashboards/03a36545488ec000/owners",
		"cells": "/api/v2/dashboards/03a36545488ec000/cells",
		"logs": "/api/v2/dashboards/03a36545488ec000/logs",
		"labels": "/api/v2/dashboards/03a36545488ec000/labels",
		"org": "/api/v2/orgs/039fb4c339500000"
	}
}
```
