### ISSUE TITLE
InfluxDB 2.0: The "views" property of "Routes" is useless [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13117]
The `Routes` schema is defined as:

```yaml
    Routes:
      properties:
        authorizations:
          type: string
          format: uri
        buckets:
          type: string
          format: uri
        dashboards:
          type: string
          format: uri
        external:
          type: object
          properties:
            statusFeed:
              type: string
              format: uri
        variables:
          type: string
          format: uri
        me:
          type: string
          format: uri
        orgs:
          type: string
          format: uri
        protos:
          type: string
          format: uri
        query:
          type: object
          properties:
            self:
              type: string
              format: uri
            ast:
              type: string
              format: uri
            analyze:
              type: string
              format: uri
            spec:
              type: string
              format: uri
            suggestions:
              type: string
              format: uri
        setup:
          type: string
          format: uri
        signin:
          type: string
          format: uri
        signout:
          type: string
          format: uri
        sources:
          type: string
          format: uri
        system:
          type: object
          properties:
            metrics:
              type: string
              format: uri
            debug:
              type: string
              format: uri
            health:
              type: string
              format: uri
        tasks:
          type: string
          format: uri
        telegrafs:
          type: string
          format: uri
        users:
          type: string
          format: uri
        write:
          type: string
          format: uri
        views:
          type: string
          format: uri
```

but the `views` property is useless, because the `views` doesn't have endpoint in API.

```bash
-> GET 
-> http://127.0.0.1:9999/api/v2/
-> {"status":"inactive","description":""}

<- 200 
<- OK
<- {
	"authorizations": "/api/v2/authorizations",
	"buckets": "/api/v2/buckets",
	"dashboards": "/api/v2/dashboards",
	"external": {
		"statusFeed": "https://www.influxdata.com/feed/json"
	},
	"labels": "/api/v2/labels",
	"me": "/api/v2/me",
	"orgs": "/api/v2/orgs",
	"protos": "/api/v2/protos",
	"query": {
		"analyze": "/api/v2/query/analyze",
		"ast": "/api/v2/query/ast",
		"self": "/api/v2/query",
		"spec": "/api/v2/query/spec",
		"suggestions": "/api/v2/query/suggestions"
	},
	"scrapers": "/api/v2/scrapers",
	"setup": "/api/v2/setup",
	"signin": "/api/v2/signin",
	"signout": "/api/v2/signout",
	"sources": "/api/v2/sources",
	"swagger": "/api/v2/swagger.json",
	"system": {
		"debug": "/debug/pprof",
		"health": "/health",
		"metrics": "/metrics"
	},
	"tasks": "/api/v2/tasks",
	"telegrafs": "/api/v2/telegrafs",
	"users": "/api/v2/users",
	"variables": "/api/v2/variables",
	"write": "/api/v2/write"
}
```
