### ISSUE TITLE
InfluxDB 2.0: The "FluxLinks" schema is useless [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13145]
I think that `FluxLinks` schema defined as:

```
FluxLinks:
      type: object
      properties:
        ast:
          type: string
          format: uri
        self:
          type: string
          format: uri
        suggestions:
          type: string
          format: uri
```

is useless and should be remove from `swagger.yml`.
