### ISSUE TITLE
InfluxDB 2.0: The "FluxSuggestions" schema doesn't respect go implementation [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13255]
The `FluxSuggestions` schema is defined as:

```yaml
FluxSuggestions:
      type: object
      properties:
        funcs:
          type: object
          properties:
            name:
              type: string
            params:
              type: object
```

but go implementation has a structure:

```go
// fluxParams contain flux funciton parameters as defined by the semantic graph
type fluxParams map[string]string

// suggestionResponse provides the parameters available for a given Flux function
type suggestionResponse struct {
	Name   string     `json:"name"`
	Params fluxParams `json:"params"`
}

// suggestionsResponse provides a list of available Flux functions
type suggestionsResponse struct {
	Functions []suggestionResponse `json:"funcs"`
}
```

The `FluxSuggestions` should be defined as:

```yaml
FluxSuggestions:
      type: object
      properties:
        funcs:
          type: array
          items:
            $ref: "#/components/schemas/FluxSuggestion"
FluxSuggestion:
      type: object
      properties:
        name:
          type: string
        params:
          type: object
          additionalProperties:
            type: string
```

and also the response type for `/query/suggestions/{name}` should be `FluxSuggestion`.

```bash
-> GET 
-> http://127.0.0.1:9999/api/v2/query/suggestions/range

<- 200 
<- OK
<- {
	"name": "range",
	"params": {
		"start": "invalid",
		"startColumn": "string",
		"stop": "invalid",
		"stopColumn": "string",
		"tables": "object",
		"timeColumn": "string"
	}
}
```
