### ISSUE TITLE
InfluxDB 2.0: The "org" query param should be same for /query and /write  [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13906]
The `/query` and the `/write` are critical parts of API 2.0 and should be friendly for users.

The `/write` endpoint has defined `org` parameter as:

```yaml
- in: query
   name: org
   description: specifies the destination organization for writes
   required: true
   schema:
      type: string
      description: all points within batch are written to this organization.
```

The `org` parameter could be `Organization.name` or `Organization.id` - [see sources](https://github.com/influxdata/influxdb/blob/master/http/write_handler.go#L137).

But the `/query` endpoint has define `org` and `orgID` parameter:
```yaml
- in: query
   name: org
   description: specifies the name of the organization executing the query; if both orgID and org are specified, orgID takes precedence.
   schema:
      type: string
- in: query
   name: orgID
   description: specifies the ID of the organization executing the query; if both orgID and org are specified, orgID takes precedence.
   schema:
      type: string
```

For consistency in API should be better that  the `/query` endpoint will be same as `/write` endpoint.

It will be also useful for clients configuration. For example both of this [Spring actuator configuration](https://github.com/bonitoo-io/influxdb-client-java/tree/master/spring#influxdb2-auto-configuration) will be valid:

```yaml
spring.influx2.url=http://localhost:9999
spring.influx2.org=my-org
spring.influx2.bucket=my-bucket
spring.influx2.token=my-token-123
spring.influx2.username=my-user
```

```yaml
spring.influx2.url=http://localhost:9999
spring.influx2.org=03d2ebc848c1e000
spring.influx2.bucket=my-bucket
spring.influx2.token=my-token
spring.influx2.username=my-user
```

Maybe it is also related to https://github.com/influxdata/influxdb-client-js/pull/115#issuecomment-490310352 from @timhallinflux
