### ISSUE TITLE
InfluxDB 2.0: The typo in Task schema: descripton -> description [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13904]
The `Task` is defined as:

```yaml
    Task:
      type: object
      properties:
        id:
          readOnly: true
          type: string
        orgID:
          description: The ID of the organization that owns this Task.
          type: string
        org:
          description: The name of the organization that owns this Task.
          type: string
        name:
          description: The name of the task.
          type: string
        description:
          descripton: An optional description of the task.
          type: string
```

but should be defined as:

```yaml
    Task:
      type: object
      properties:
        id:
          readOnly: true
          type: string
        orgID:
          description: The ID of the organization that owns this Task.
          type: string
        org:
          description: The name of the organization that owns this Task.
          type: string
        name:
          description: The name of the task.
          type: string
        description:
          description: An optional description of the task.
          type: string
```

introduced by https://github.com/influxdata/influxdb/pull/13850, cc @AlirieGray
