### ISSUE TITLE
InfluxDB 2.0: The swagger.yml doesn't contains resource types for Notifications

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#14513]
The https://github.com/influxdata/influxdb/pull/14450 add new ResourceTypes:
- `notificationRules`
- `notificationEndpoints`

but the swagger doesn't contains these types:

```yaml
Permission:
      required: [action, resource]
      properties:
        action:
          type: string
          enum:
            - read
            - write
        resource:
          type: object
          required: [type]
          properties:
            type:
              type: string
              enum:
                - authorizations
                - buckets
                - dashboards
                - orgs
                - sources
                - tasks
                - telegrafs
                - users
                - variables
                - scrapers
                - secrets
                - labels
                - views
                - documents
            id:
              type: string
              nullable: true
              description: if id is set that is a permission for a specific resource. if it is not set it is a permission for all resources of that resource type.
            name:
              type: string
              nullable: true
              description: optional name of the resource if the resource has a name field.
            orgID:
              type: string
              nullable: true
              description: if orgID is set that is a permission for all resources owned my that org. if it is not set it is a permission for all resources of that resource type.
            org:
              type: string
              nullable: true
              description: optional name of the organization of the organization with orgID.
```

__Expected definition in swagger:__
```yaml
Permission:
      required: [action, resource]
      properties:
        action:
          type: string
          enum:
            - read
            - write
        resource:
          type: object
          required: [type]
          properties:
            type:
              type: string
              enum:
                - authorizations
                - buckets
                - dashboards
                - orgs
                - sources
                - tasks
                - telegrafs
                - users
                - variables
                - scrapers
                - secrets
                - labels
                - views
                - documents
                - notificationRules
                - notificationEndpoints
            id:
              type: string
              nullable: true
              description: if id is set that is a permission for a specific resource. if it is not set it is a permission for all resources of that resource type.
            name:
              type: string
              nullable: true
              description: optional name of the resource if the resource has a name field.
            orgID:
              type: string
              nullable: true
              description: if orgID is set that is a permission for all resources owned my that org. if it is not set it is a permission for all resources of that resource type.
            org:
              type: string
              nullable: true
              description: optional name of the organization of the organization with orgID.
```

cc @kelwang
