### ISSUE TITLE
Meta query crashes UI

### ISSUE THREAD

**Issue by jlapacik** [influxdata/influxdb#14566]
A call to `tagValues` caused the UI to return the following error message:

<img width="1625" alt="ui_crash" src="https://user-images.githubusercontent.com/22945345/62493022-dfcf9480-b784-11e9-927a-b41023bbf482.png">

Steps to reproduce:

1. Create the following toml file:

    ```toml
    title = "Documented schema"
    [[measurements]]
    name = "mem"
    tags = [
        { name = "AYx2mIOn58", source = { type = "sequence", format = "AYx2mIOn58-%s", start = 0, count = 5000000 } },
        { name = "next", source = { type = "sequence", format = "next-%s", start = 0, count = 2 } },
    ]
    fields = [
        # An example of a sequence of integer values
        { name = "free", count = 10, source = 25, time-interval = "1h" },
        { name = "consumed", count = 1000, source = 25.5, time-precision = "m" },
    ]
    ```
2. Generate the series defined in the above file(influxd should not be running):
```
influxd generate <schema.toml> --org <org> --bucket <bucket> --clean all
```
3. Run `influxd`.
4. Pull up the UI `http://localhost:9999`.
5. Navigate to the data explorer and issue the following flux query:
    ```
    import "influxdata/influxdb/v1"
    
    v1.tagValues(bucket:"b", tag:"AYx2mIOn58")
    ```
    This query should return `3748952` rows (~70MB of uncompressed data).

Note I am using firefox 68.0.1
