### ISSUE TITLE
Modify tasks API to include a field to track the last run status and error

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#15153]
## Overview

Add new fields to the [task object](https://github.com/influxdata/influxdb/blob/a8ad9e26150453b9987dcfc1f6de4f9cf15b9c36/http/swagger.yml#L7015) track the last run, queryable via the [tasks](https://github.com/influxdata/influxdb/blob/a8ad9e26150453b9987dcfc1f6de4f9cf15b9c36/http/swagger.yml#L4201-L4202) API

* `lastRunStatus`, which is a subset of the `Run` `status`, as follows:

```yaml
        lastRunStatus:
          readOnly: true
          type: string
          enum:
            - failed
            - success
            - canceled
```

* `lastRunError` will store the last error message in the run log when the `lastRunStatus` contains a value of `failed`.
* If `lastRunStatus` is canceled or success, `lastRunError` should be cleared

The end goal is this value can be shown on the task overview screen in Chronograf.
