### ISSUE TITLE
influx cli support multiple profiles

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/influxdb#15302]
as of now you can configure the `influx` cli with either `INFLUX_HOST` and `INFLUX_TOKEN` or the token setup in `~/.influxdbv2/credentials` and this is a good starting point.

But soon will rise the need to be handling multiple instances and endpoints or credentials for th e same instance for testing/debug purposes. I'd like to be able to have profiles just like the `aws` cli with the `~/.influxdbv2/credentials` file looking something like

```toml
[default]
address = "http://localhost:9999"
token = "xxxxx"

[staging]
address = "https://example.com:9999"
token = "xxxx"

[frankfurt]
address = "https://eu-central-1-1.aws.influxcloud.net"
token = "xxxx"
```

and the usage can be along the lines of `influx --profile=frankfurt bucket find` or setup the `INFLUX_PROFILE=frankfurt` env variable
