### ISSUE TITLE
influxDB2.0 alpha - http custom base path

### ISSUE THREAD

**Issue by steverweber** [influxdata/influxdb#15721]
Trying to serve influxdb v2.0alpha through nginx proxy because I need to run multiple websites on the same host while admins only allow one port to be open 443.

`https://dnsname/influxdb2`

influxdb http page is referencing the root url path to load the site `.js` also noticed `<base href="/"> ` is the url root.

is their some header that I should be passing upstream to influxdb so it knows to use a different basepath? or could an option be added to influxd so the pass path can be custom?

Thanks!

```
<!doctype html>
<html>
<head><meta http-equiv="Content-type" content="text/html;charset=utf-8width=device-width,initial-scale=1" name="viewport"><title>InfluxDB 2.0</title><base href="/">
<link rel="shortcut icon" href="/favicon.ico"></head>
<body><div id="react-root" data-basepath=""></div>
<!-- want this to be something like: influxdb2/a02e0ac4f4.js  or a02e0ac4f4.js and use base href="/influxdb2/" -->
<script src="/a02e0ac4f4.js"></script>
</body></html>
```

**Comment by steverweber** [comment]
looking at the code `git checkout v2.0.0-alpha.19` i see some env vars... but setting them didn't help.

systemd...
```
Environment="STATIC_PREFIX=/influxdb2/"
Environment="API_PREFIX=/influxdb2/"
Environment="BASE_PATH=/influxdb2/"
Environment="API_BASE_PATH=/influxdb2/"
ExecStart=/srv/influxd
```

also seems that the option is in Chronograf looking at the readme
```
./chronograf/README.md:Change the default root path of the Chronograf server with the `--basepath`
```
perhaps this should be made available on `influxd --basepath=/influxdb2/`

**Comment by steverweber** [comment]
please provide some feedback before closing.
Thanks.

**Comment by drdelambre** [comment]
For the base path parameters.. those are for configuring the frontend during compilation to allow it to be run behind a proxy, so they're already baked in by the time the image is pushed to the registry. Here's an example dockerfile that I use when i want to expose the frontend on a different url, passing those environment variables as build ARGs:
```Dockerfile
FROM ubuntu:bionic AS base

RUN apt-get update -y && \
    apt-get install -y \
        nginx \
        build-essential \
        curl \
        git

FROM base AS repo
WORKDIR /repo

ARG STATIC_DIRECTORY
ARG BASE_PATH
ARG API_BASE_PATH

ENV PATH="/node/bin:${PATH}"
RUN mkdir /node && \
    curl -sL https://git.io/n-install | N_PREFIX=/node bash -s -- -q && \
    npm i -g yarn

RUN git clone git://github.com/influxdata/influxdb.git && \
    cd ./influxdb

WORKDIR /repo/influxdb/ui

# these are all run together as docker's caching mechanism
# makes big steps like yarn install expensive
RUN yarn install --production=false && \
    yarn generate && \
    INFLUXDB_SHA=remote $(npm bin)/webpack --config ./webpack.prod.ts --bail && \
    rm -rf ./node_modules

FROM base AS deploy
WORKDIR /repo
COPY --from=repo /repo/influxdb/ui/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN useradd --no-create-home nginx

CMD ["nginx", "-g", "daemon off;"]
```

with just a simple nginx config in `./nginx.conf` that hosts the files in `/usr/share/nginx/html' as your desired path:
```
  server {
    listen [::]:80;
    listen 80;

    server_name _;

    # Path for static files
    root /usr/share/nginx/html;

    location / {
      try_files $uri /index.html;
    }
  }
```

**Comment by kwinkel** [comment]
Rebuilding the UI with a variable seems not to be a solution. Setting an environment variable to override the `base href` and/or taking this from the request `X-Forwarded-Prefix` would be necessary to run influxdb2 behind a proxy.

**Comment by CLKBlu3** [comment]
Having a similar issue.
I did follow https://gist.github.com/mvadu/5fbb7f5676ce31f2b1e6 from an older version to try setting up things.
However, it only loads the login page at http://mydomain.com/influxdb/, which doesn't work.

My setup is:
(relevant parts only)
nginx.conf:
```
upstream influxdb {
		server localhost:8086;
		keepalive 10;
	}
	#check the referer to identify requests originated by Influx UI
	map $http_referer $proxyloc {	
		~*influx influxdb;
	}
	
	#Influx Web API end points
	map $request_uri $backend {	
		~*query influxdb;
		~*write influxdb;
		~*ping  influxdb;
	}
```

server conf:
```
[...]
location / {
		if ($backend) {
			return 302 /$backend/$request_uri;
		}
	
		if ($proxyloc) {
			return 302 /$proxyloc/$uri;
		}
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	
	location /influxdb/ {
			
		proxy_pass	   http://localhost:8086/;
		proxy_set_header   Host			$http_host;
		proxy_set_header   X-Real-IP		$remote_addr;
		proxy_set_header   X-Forwarded-For	$proxy_add_x_forwarded_for;
	}
[...]
```

As said, my current configuration seems to load the login page fine, but it's unfunctional as it doesn't allow me access it.

Note: I use the docker container for influxdb2.0 beta from https://quay.io/repository/influxdb/influxdb?tag=2.0.0-beta&tab=tags

**Comment by cappelaere** [comment]
Similar issue!  Grrrrrr!

**Comment by lephisto** [comment]
Is there any progress on this? I would really like to put Influx 2 OSS behind a reversproxy.

**Comment by nikosamus** [comment]
Same happening here, can't reverse proxy Influx 2.0. Even after many hours trying with apache html proxy for rewriting urls I can't get it working.

**Comment by CLKBlu3** [comment]
For people that had the same issue I did (commented a few months ago). 
We managed to make it work by using subdomains. So if you have a domain (we got our certs with Certbot), I can recommend trying this. 
We registered ours as `mysubdomain.mydomain.com`  (sample name, obviously)
This way, all the paths should work, since we do not have a "custom" base path as we used to, but instead have a new "root" path that can match influxdb's ones without messing our configuration.

Sample nginx configuration:
```nginx
server {
        server_name     mysubdomain.mydomain.com;

        location / {

                #access_log /var/log/nginx/influx-access.log influx buffer=1024 flush=5m;
                proxy_pass         http://localhost:xxxx/;
                proxy_set_header   Host                 $http_host;
                proxy_set_header   X-Real-IP            $remote_addr;
                proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
        }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mysubdomain.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mysubdomain.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
[...] # Other conf stuff

```

**Comment by steverweber** [comment]
seems the only solution to date is recompiling the source code because the path is baked in.
workarounds:
 - give-up and use a different hostname or a subdomain.
 - write some hacky nginx config that might work? and then might break after some updates to influxdb

Guess i'll just continue to ignore the influx UI and use the CLI for the odd admin task. Grafana runing under a custom base url is working out well for viewing data and setting alerts.

**Comment by YassineElbouchaibi** [comment]
Having the same issue... I just spent about 4 hours on it before finding this thread... For now I think I'll have to go with subdomain as no matter how I mess with the nginx config even if I get some web pages to load, some network requests just won't...

**Comment by ondrej-ivanko** [comment]
Spend few days on this issue. So far it seems unresolvable.

I needed to use InfluxDB UI behing Ingress reverse proxy. With only one ingress-controller for the whole cluster. Turns out path based routing is possible with rewritte-target annotation of nginx controller.

Despite that, what ultimately cancelled any effort to use Ingress was that `<base href="/">` thing, which doused any effort for us to use Ingress.

We would welcome any customization of base_href path, possibly via helm chart as we're using that for deployment.

**Comment by gvasanka** [comment]
Having the same issue, spent almost a day finding a solution with trying out different configs.  finally, I am here :)

> Turns out path based routing is possible with rewrite-target annotation in Ingress resource. But the Influx UI does not display at all.

@ondrej-ivanko I hope what you mean is,  you could access the influx DB API endpoints(write and query) using the path-based routing approach. but no luck in accessing UI.

If that's true can you share the working config with rewrite-target annotation?

**Comment by ondrej-ivanko** [comment]
@gvasanka I can't confirm that accessing API endpoints with `rewrite-target` annotation will work, as I haven't tried it. I don't see any reason, why it shouldn't work though.

> If that's true can you share the working config with rewrite-target annotation?

 Our company decided to abandon the effort to use Ingress controller. We just use port-forwarding of Influx pod for accessing UI.

**Comment by gvasanka** [comment]
@ondrej-ivanko  Thank you very much for your answer. 

I was able to get access to influxDb 2 API with the below Ingress config. Posting it here for other's usage in case somebody struggling. 


```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: influx-ingress-test
spec:
  rules:
  -  http:
      paths:
      - backend:
          serviceName: influxdb-release
          servicePort: 8086
        path: /influx(/|$)(.*)
```


But still no luck in getting access to the web.

**Comment by ecospecifier** [comment]
How is this not receiving more attention? Please can we get acknowledgement of the issue and get ENV access to set the base path like grafana has or appending to request url like even simple containers like adminer has. Apologies if I sound crass but having this hardcoded in is ridiculous. Running behind a reverse proxy nginx is something many people do and having to setup a subdomain just to workaround a HARDCODED base url is really silly.

Please try and give us some real commitment on this guys!

**Comment by RavilN** [comment]
I have a similar issue!

**Comment by jjriggs** [comment]
Would like to also add my complaint to this thread. Grafana has a root_url parameter you can set in the config file. As far as I can tell, that is not the case with InfluxDB. Very frustrating that there appears to be no way for it to reside behind a reverse proxy without a subdomain.

**Comment by ingaa85** [comment]
I would also need this feature, as i dont want to use a second subdomain for this.

**Comment by UnKnoWn-Consortium** [comment]
From the commit that updates the UI version, it appears the UI releases are downloaded into this repo and get bundled into the go build. FYI: https://github.com/influxdata/influxdb/pull/21564/files

In that UI release bundle, ```<base href="/">``` is already set. I think we should open a mirrored issue at the [UI repo](https://github.com/influxdata/ui) too.

**Comment by TravisDuck999** [comment]
Having the same problem here, really thought it would be a simple setting to change when I started this.

Would love to see this updated, has anyone had any luck ?

**Comment by mitchellkingsley** [comment]
Expressing my interest. I don't want to have to rebuild, and I don't want to use subdomains. Given Grafana has this feature and is commonly a part of the stack, I would hope that Influx soon has the same functionality.

**Comment by Keviinplz** [comment]
any update on this? :(

**Comment by ecospecifier** [comment]
Also checking back to see if there is any update on this, seems not.

**Comment by thomas725** [comment]
Just stumbled upon this problem too. Hopefully this will be addressed soon.

**Comment by cavepopo** [comment]
Just spent one day trying to make this work and ended here.

+1 for this custom param !

**Comment by nick-jansen** [comment]
+1

**Comment by mattp0** [comment]
Still a problem and I am still hopeful for a solution. Wanted to also add that Grafana supports proxy auth and it would be nice if influx2.0 could be setup for SSO via a tool like vouch proxy.

**Comment by h3po** [comment]
+1

**Comment by tantrum-junkie** [comment]
I am also trying to get the Influxdb v2 WebGUI to work behind an Apache web-proxy.

So far I have the a configuration which kinda works:
- The login page shows up fine and I can login ok
- Also any calls that I make directly to the API (/influx/api/v2/*) seem to work correctly
- I cannot see any errors in the firefox network tab

BUT after successful login the influx GUI shows me:
 "404 Bummer! We couldn't find the page you were looking for"

Does anybody have an idea what I am missing?
I have a feeling it has something to do with how the used JS framework resolves its' pages.
See my current configuration below.

 ```
   <Proxy balancer://influxcluster>
        BalancerMember http://10.27.xx.xx:8086 route=influx
        ProxySet stickysession=JSESSIONID
        ProxySet lbmethod=byrequests
    </Proxy>

    <Location /influx>
        ProxyPass         balancer://influxcluster
        ProxyPassReverse  balancer://influxcluster

        AddOutputFilterByType SUBSTITUTE text/javascript text/html text/css application/json
        SubstituteMaxLineLength 10m
        Substitute "s#(href|src|path|a\.p)=(\"|\')\.?/#$1=$2/influx/#q"
        Substitute "s#(\'|\"|\`|\})(/api|/signin|/health|/metrics|/debug)#$1/influx$2#q"
    </Location>
```

**Comment by IngoDbg** [comment]
+1

**Comment by nicko170** [comment]
+1

**Comment by zychu312** [comment]
+1

**Comment by Mixka** [comment]
Please, stop these "+1" and other non-content messages. It does not help anyone or this case. Just unnecessary clutter in the comment feed.

If you want to get notifications click "Subscribe". If you have the same problem and like to get it fixed, add a reaction to the first message.

**Comment by MatthiasWerning** [comment]
We would also like to run the InfluxDB UI behind a reverse proxy using Ingress, since a subdomain based approach is not feasible in our architecture. I tried to get the UI running using @steverweber approach with the referer filtering in nginx.

I got it working for the login screen and authentication using the API, but now I'm stuck at the internal React based routing. The only issue is not even just the base tag in the index.html but also all React routes which also begin with / altogether.

Btw if you're trying this solution as well, you also have to rewrite the session cookie path from /api to another path which could also pose a security issue by allowing other applications on your host to read the session cookie. You also gotta return a 307, since 302 does not preserve the original HTTP method (POST will turn into GET and thus auth will failed).

This issue is now open for 1.5 years and unfortunately there seems to be no feasible and not super hacky solution to use InfluxDB UI under a specific sub-path.

**Comment by morix-gao** [comment]
+1

**Comment by 1naboki1** [comment]
I cant see the point why this feature is not available - even as OSS. Marketingwise its like preventing users too see our logo....

+1

**Comment by realies** [comment]
bump

**Comment by SaswatPadhi** [comment]
There are 46 comments on this thread and over a hundred +1's if we add them up.

Please comment as to why this issue is marked as `wontfix` (but is still left open?!)

**Comment by memetb** [comment]
I have a hacked nginx configuration as follows that does it almost all, however I need someone to push it passed to touchdown line with regards to the front end.

The following configuration indirects the backend entirely (as far as the server is concerned, the front end calls look exactly as though they were coming from /).

It also solves most of the front end (I can browser-debug and see the api calls being made and correctly fetching data - including logging in correctly).

It also injects into the `process.env.*` values as referenced [here](https://github.com/influxdata/ui/blob/c2e66b2d87102e6495aa1e9d33f5838e8e48b462/src/shared/constants/index.ts#L67-L72) in an attempt to make routing "just work". I can confirm via browser-debug that the values are present at the `render` call for the root.

Unfortunately, I still get a 404 on the ui. I am hoping this is something minor in the frontend, and that I just need to specify a different process.env value.

I would appreciate any frontend devs to chime in if they have any insights.

```nginx
upstream influx {
    server 10.0.0.5:8086;
}

map $http_referer $munged_referer {
        "~^(?<prefix>.*)/influx(?<suffix>.*)$" $prefix$suffix;
}

server {
        listen 80;

        location ~ ^/signin(.*) {
                # this may or may not be necessary if the base path injection for the webpack makes a difference
                rewrite ^/signin(.*)$ /influx/signin$1 last;
        }

        location = /influx/env.js {
                # webpack process.env.* injection
                add_header Content-Type application/javascript;
                return 200 "var prefix='/influx/'; process = {'env' : {'STATIC_PREFIX':prefix,'API_PREFIX':prefix, 'BASE_PATH': prefix, 'API_BASE_PATH':prefix}};";
        }

        location = /influx {
                proxy_pass http://influx$1;
                proxy_redirect off;

                # inject environment for front-end webpack
                sub_filter '</head>' '<script type="text/javascript" src="/influx/env.js"></script></head>';

                # inject relative path to html root
                sub_filter 'href="/' 'href="/influx/';
                sub_filter 'src="/' 'src="/influx/';
                sub_filter_types text/css text/javascript application/javascript application/json;
                sub_filter_once off;
        }

        location ~ ^/influx(.*) {
                proxy_pass http://influx$1;
                proxy_redirect off;

                # tricks to make the server completely unaware of the redirection
                proxy_set_header Host $host;
                proxy_set_header Referer $munged_referer;
                proxy_cookie_path / /influx/;

                # rewrite API endpoint advertisments
                sub_filter '/api/v2' '/influx/api/v2';

                # rewrite endpoints which seem to be hard-coded in js. We also could url rewrite them as we do for login...
                sub_filter '/health' '/influx/health';
                sub_filter '"/logout' '"/influx/logout';

                # rewrite index.html specifically
                sub_filter_types text/css text/javascript application/javascript application/json;
                sub_filter_once off;
        }

        location / {
                  # ...
        }
}
```

**Comment by elyancorrea** [comment]
+1

**Comment by dgeisse** [comment]
+1

**Comment by depermana12** [comment]
+1

**Comment by matheusbrunetti** [comment]
+1

**Comment by arun-prakash-fokus** [comment]
This is solution based on `traefik`

```yml
version: "3.9"
name: traefik-influxdb
services:
  influxdb:
    image: influxdb:2.6.1
    expose:
    - 8086
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.influxdb_strip.stripprefix.prefixes: /influxdb
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.lastModified: "true"
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[0].regex: src="/
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[0].replacement: src="/influxdb/
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[1].regex: href="/
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[1].replacement: href="/influxdb/
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[2].regex: data-basepath="
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[2].replacement: data-basepath="/influxdb/
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[3].regex: n.p="/"
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[3].replacement: n.p="/influxdb/"
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[4].regex: \)}/health`
      traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[4].replacement: )}/influxdb/health`
      traefik.http.routers.influxdb.entrypoints: websecure
      traefik.http.routers.influxdb.middlewares: rewrite-foo, influxdb_strip
      traefik.http.routers.influxdb.rule: PathPrefix(`/influxdb`) || PathPrefix(`/api`)
      traefik.http.routers.influxdb.tls: "true"
      traefik.http.services.influxdb.loadbalancer.server.port: "8086"
    networks:
      - default
    volumes:
      - influxdb.config:/etc/influxdb2
      - influxdb.data:/var/lib/influxdb2
  traefik:
    image: traefik:v2.9.6
    ports:
    - 5443:443
    environment:
      TRAEFIK_API_INSECURE: "false"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: :443
      TRAEFIK_EXPERIMENTAL_LOCALPLUGINS_REWRITE_MODULENAME: github.com/traefik/plugin-rewritebody
      TRAEFIK_LOG_LEVEL: DEBUG
      TRAEFIK_PING: "true"
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_PROVIDERS_DOCKER_SWARMMODE: "false"
      TRAEFIK_PROVIDERS_FILE_FILENAME: /etc/traefik/config.yml
      TRAEFIK_PROVIDERS_FILE_WATCH: "true"
    healthcheck:
      test:
      - CMD-SHELL
      - traefik healthcheck --ping
      timeout: 5s
      interval: 10s
      retries: 5
      start_period: 5s
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.traefik-auth.basicauth.users: admin:$$apr1$$8EVjn/nj$$GiLUZqcbueTFeD23SuB6x0
      traefik.http.middlewares.traefik-strip.stripprefix.prefixes: /traefik
      traefik.http.routers.traefik_https.entrypoints: websecure
      traefik.http.routers.traefik_https.middlewares: traefik-auth,traefik-strip
      traefik.http.routers.traefik_https.rule: Host(`example.localhost`) && (PathPrefix(`/traefik`) || HeadersRegexp(`Referer`, `.*/traefik/.*`))
      traefik.http.routers.traefik_https.service: api@internal
      traefik.http.routers.traefik_https.tls: "true"
      traefik.http.services.traefik.loadbalancer.server.port: "443"
    networks:
      - default
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # default docker context
      - /run/user/1000/docker.sock:/var/run/docker.sock # rootless docker context
      - ./traefik/plugins-local:/plugins-local
volumes:
  influxdb.config:
    name: influxdb-1-config
  influxdb.data:
    name: influxdb-1-data
```

In the browser, influxdb can be reached over

https://example.localhost/influxdb

![Screenshot from 2023-03-17 10-27-03](https://user-images.githubusercontent.com/25454690/225865670-11c36331-875f-44c8-9932-5787abf3c898.png)

The `influxdb api` can be reached over 

https://example.localhost/influxdb/api/v2 or https://example.localhost/api/v2 

```bash
curl --insecure --location --request GET 'https://example.localhost:5443/influxdb/api/v2' \
--header 'Authorization: Token rEOYqouq5Vl4atAb4bGDox3vqNX_X0Tn2yHJV7jRqPlRz1lK0XxAiOLZADyulrdTCJ8nkmBNF_VjkmDAwLkODg==' \
--data-raw ''
```

```json
{
    "authorizations": "/api/v2/authorizations",
    "backup": "/api/v2/backup",
    "buckets": "/api/v2/buckets",
    "checks": "/api/v2/checks",
    "dashboards": "/api/v2/dashboards",
    "delete": "/api/v2/delete",
    "external": {
        "statusFeed": "https://www.influxdata.com/feed/json"
    },
    "flags": "/api/v2/flags",
    "labels": "/api/v2/labels",
    "me": "/api/v2/me",
    "notificationEndpoints": "/api/v2/notificationEndpoints",
    "notificationRules": "/api/v2/notificationRules",
    "orgs": "/api/v2/orgs",
    "plugins": "/api/v2/telegraf/plugins",
    "query": {
        "analyze": "/api/v2/query/analyze",
        "ast": "/api/v2/query/ast",
        "self": "/api/v2/query",
        "suggestions": "/api/v2/query/suggestions"
    },
    "restore": "/api/v2/restore",
    "scrapers": "/api/v2/scrapers",
    "setup": "/api/v2/setup",
    "signin": "/api/v2/signin",
    "signout": "/api/v2/signout",
    "sources": "/api/v2/sources",
    "swagger": "/api/v2/swagger.json",
    "system": {
        "debug": "/debug/pprof",
        "health": "/health",
        "metrics": "/metrics"
    },
    "tasks": "/api/v2/tasks",
    "telegrafs": "/api/v2/telegrafs",
    "users": "/api/v2/users",
    "variables": "/api/v2/variables",
    "write": "/api/v2/write"
}
```

The drawback of this solution is that no other docker service can be exposed over the `/api` path as it is currently used by the `influxdb` traefik label rule

`traefik.http.routers.influxdb.rule: PathPrefix(`/influxdb`) || PathPrefix(`/api`)`

Maybe someone can help figure out how to run the influxdb api in a subpath location.

**Comment by bodak** [comment]
Thanks @robertohdzrz! This works great.
For those who prefer to not use Traefik Hub and have it disabled, you can add the plugin as follows using Helm values:

```
  initContainers:
    - name: traefik-plugins-2
      image: k8s.gcr.io/git-sync/git-sync:v3.6.5
      args: ["-v", "6"]
      volumeMounts:
        - name: traefik
          mountPath: /plugins-local
      env:
        - name: GIT_SYNC_REPO
          value: https://github.com/traefik/plugin-rewritebody
        - name: GIT_SYNC_REV
          value: "v0.3.1"
        - name: GIT_SYNC_ROOT
          value: /plugins-local/src/github.com/traefik/
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_LINK
          value: plugin-rewritebody
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
 ...
 additionalArguments:
    - "--experimental.localplugins.plugin-rewritebody.modulename=github.com/traefik/plugin-rewritebody"
 ...
 persistence:
    enabled: true
    name: traefik
    accessMode: ReadWriteOnce
    size: 256Mi
    path: /plugins-local
    annotations: {}
```

**Comment by kulmann** [comment]
@arun-prakash-fokus thank you for your example config, that helped me a lot! I'd like to add some additions to your proposed solution:

1. with influxdb `v2.7.1` the base path in the initially loaded .js file is stored in the variable `o.p`, not `n.p`. Seems like the var name just changed in the uglify step... had to adjust the rewritebody rule no. 3 accordingly:
```yaml
traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[3].regex: o.p="/"
traefik.http.middlewares.rewrite-foo.plugin.rewrite.rewrites[3].replacement: o.p="/influxdb/"
```

2. my setup is properly working without exposing port 8086. I configured my application to use the web entrypoint port exposed by `traefik` and then of course concatenated with my `/influxdb` path prefix.

3. for anyone wondering how the folder structure in `plugins-local` needs to look like for traefik to find the plugin:
```
./plugins-local/src/github.com/traefik/plugin-rewritebody
```

Just put the content of the `plugin-rewritebody` repo into that folder and apply the plugin config like proposed by @arun-prakash-fokus then you're good to go with the plugin.

**Comment by jdeus** [comment]
Any news ? Seems like a basic feature to have ...

**Comment by gbravery** [comment]
OK, I have a stupid question - wondering if anyone can help.

Does the "work around" proposed by [arun-prakash-fokus](https://github.com/influxdata/influxdb/issues/15721#issuecomment-1473533962) with the tweak proposed by [kulmann](https://github.com/influxdata/influxdb/issues/15721#issuecomment-1546891798) still work?

As in my set up, it re-writes the html pages, but it's ignoring the javascript pages for some reason.

Influx is 2.7.1
Traefik is 2.10.4

I'm using chain middleware to join stripprefix and rewrite-body (tried the traefik and the packruler version):
  middlewares:
    influxdb-strip-prefix:
      stripprefix:
        prefixes:
          - /influxdb
    influxdb-rewrite:
      plugin:
        rewrite-gzip-body:
          lastModified: true
          loglevel: -1
          rewrites:
            - regex: src="/
              replacement: src="/influxdb/
            - regex: href="/
              replacement: href="/influxdb/
            - regex: data-basepath="
              replacement: data-basepath="/influxdb/
            - regex: n.p="/"
              replacement: n.p="/influxdb/"
            - regex: o.p = "/"
              replacement: o.p = "/influxdb/"
            - regex: \)}/health`
              replacement: )}/influxdb/health`
          monitoring:
            methods:
              - GET
            types:
              - text/html
              - text/javascript
    influxdb-chain:
      chain:
        middlewares:
          - influxdb-rewrite
          - influxdb-strip-prefix

**Comment by gbravery** [comment]
OK, I have a stupid question - wondering if anyone can help.

Does the "work around" proposed by [arun-prakash-fokus](https://github.com/influxdata/influxdb/issues/15721#issuecomment-1473533962) with the tweak proposed in https://github.com/influxdata/influxdb/issues/15721#issuecomment-1546891798

Still work? As in my set up, it re-writes the html pages, but it's ignoring the javascript pages for some reason.

Influx is 2.7.1
Traefik is 2.10.4

I'm using chain middleware to join stripprefix and rewrite-body (tried the traefik and the packruler version):
```
  middlewares:
    influxdb-strip-prefix:
      stripprefix:
        prefixes:
          - /influxdb
    influxdb-rewrite:
      plugin:
        rewrite-gzip-body:
          lastModified: true
          loglevel: -1
          rewrites:
            - regex: src="/
              replacement: src="/influxdb/
            - regex: href="/
              replacement: href="/influxdb/
            - regex: data-basepath="
              replacement: data-basepath="/influxdb/
            - regex: n.p="/"
              replacement: n.p="/influxdb/"
            - regex: o.p = "/"
              replacement: o.p = "/influxdb/"
            - regex: \)}/health`
              replacement: )}/influxdb/health`
          monitoring:
            methods:
              - GET
            types:
              - text/html
              - text/javascript
    influxdb-chain:
      chain:
        middlewares:
          - influxdb-rewrite
          - influxdb-strip-prefix

```
> 

FWIW, I have managed to make this work - but not using packruler plugin.
I've also managed to redirect the API...

```
experimental:
  plugins:
    cookiePathPrefix:
      modulename: "github.com/SchmitzDan/traefik-plugin-cookie-path-prefix"
      version: "v0.0.3"
    rewrite-body:
      moduleName: "github.com/traefik/plugin-rewritebody"
      version: "v0.3.1
      
http:
  routers:
    household_influxdb:
      rule: Host(`my-host`) && ( PathPrefix(`/influxdb`) || PathPrefix(`/influxdb/`))
      service: household-influxdb
      entrypoints:
        - "web"
      middlewares: influxdb-cookie-path, influxdb-rewrite2, influxdb-strip-prefix
      
  middlewares:
    influxdb-cookie-path:
      plugin:
        cookiePathPrefix:
          prefix: "influxdb"
    influxdb-strip-prefix:
      stripprefix:
        prefixes:
          - /influxdb
    influxdb-rewrite2:
      plugin:
        rewrite-body:
          lastModified: true
          rewrites:
            - regex: src="/
              replacement: src="/influxdb/
            - regex: href="/
              replacement: href="/influxdb/
            - regex: data-basepath="
              replacement: data-basepath="/influxdb/
            - regex: n.p="/"
              replacement: n.p="/influxdb/"
            - regex: o.p="/"
              replacement: o.p="/influxdb/"
            - regex: /api/
              replacement: /influxdb/api/
            - regex: api/v2/query
              replacement: influxdb/api/v2/query
            - regex: \)}/health`
              replacement: )}/influxdb/health`
```"
This isn't extensively tested - but I have made sure I can login, see data, etc.
There might be a better way of writing the regex too - the first /api/ covered a lot of the calls, but there was a specific hidden one that used api/v2/query. However, the /api/ is a bit to "general" and not targeted very well.
      
FWIW, I still think it would be better if InfluxDB had this built in!

**Comment by gbravery** [comment]
OK, I have a stupid question - wondering if anyone can help.

Does the "work around" proposed by [arun-prakash-fokus](https://github.com/influxdata/influxdb/issues/15721#issuecomment-1473533962) with the tweak proposed in https://github.com/influxdata/influxdb/issues/15721#issuecomment-1546891798

Still work? As in my set up, it re-writes the html pages, but it's ignoring the javascript pages for some reason.

Influx is 2.7.1
Traefik is 2.10.4

I'm using chain middleware to join stripprefix and rewrite-body (tried the traefik and the packruler version):
```
  middlewares:
    influxdb-strip-prefix:
      stripprefix:
        prefixes:
          - /influxdb
    influxdb-rewrite:
      plugin:
        rewrite-gzip-body:
          lastModified: true
          loglevel: -1
          rewrites:
            - regex: src="/
              replacement: src="/influxdb/
            - regex: href="/
              replacement: href="/influxdb/
            - regex: data-basepath="
              replacement: data-basepath="/influxdb/
            - regex: n.p="/"
              replacement: n.p="/influxdb/"
            - regex: o.p = "/"
              replacement: o.p = "/influxdb/"
            - regex: \)}/health`
              replacement: )}/influxdb/health`
          monitoring:
            methods:
              - GET
            types:
              - text/html
              - text/javascript
    influxdb-chain:
      chain:
        middlewares:
          - influxdb-rewrite
          - influxdb-strip-prefix

```
> 

FWIW, I have managed to make this work - but not using packruler plugin.
I've also managed to redirect the API...

```
experimental:
  plugins:
    cookiePathPrefix:
      modulename: "github.com/SchmitzDan/traefik-plugin-cookie-path-prefix"
      version: "v0.0.3"
    rewrite-body:
      moduleName: "github.com/traefik/plugin-rewritebody"
      version: "v0.3.1
      
http:
  routers:
    household_influxdb:
      rule: Host(`my-host`) && ( PathPrefix(`/influxdb`) || PathPrefix(`/influxdb/`))
      service: household-influxdb
      entrypoints:
        - "web"
      middlewares: influxdb-cookie-path, influxdb-rewrite2, influxdb-strip-prefix
      
  middlewares:
    influxdb-cookie-path:
      plugin:
        cookiePathPrefix:
          prefix: "influxdb"
    influxdb-strip-prefix:
      stripprefix:
        prefixes:
          - /influxdb
    influxdb-rewrite2:
      plugin:
        rewrite-body:
          lastModified: true
          rewrites:
            - regex: src="/
              replacement: src="/influxdb/
            - regex: href="/
              replacement: href="/influxdb/
            - regex: data-basepath="
              replacement: data-basepath="/influxdb/
            - regex: n.p="/"
              replacement: n.p="/influxdb/"
            - regex: o.p="/"
              replacement: o.p="/influxdb/"
            - regex: /api/
              replacement: /influxdb/api/
            - regex: api/v2/query
              replacement: influxdb/api/v2/query
            - regex: \)}/health`
              replacement: )}/influxdb/health`
```
  
This isn't extensively tested - I've made sure I can login, see data, etc.
