### ISSUE TITLE
Matching notification rule tag parameters should combine multiple tags with OR instead of AND

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#16017]
currently https://github.com/influxdata/influxdb/blob/0dc5c2af92f910f7f6bd9e6a7a4bfdbd4b255805/http/swagger.yml#L5583
```        
- in: query
  name: tag
  description: Only show notification rules that match a tag pair. Uses `AND` to specify multiple tags.
  schema:
    type: string
    pattern: ^[a-zA-Z0-9_]+:[a-zA-Z0-9_]+$
    example: env:prod
```

if check status has tags `[k1:v1, k2:v2]` it is matched by notification rule NR1 which matches tags `[k1:v1]`
A GET to `/api/v2/notificationRules` with query parameters `tag: k1:v1 tag: k2:v2` should return NR1. 
Currently only query parameters `tag: k1:v1` returns NR1
