### ISSUE TITLE
Pkger field referencing within a package

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16473]
As a user, I'd like the ability to reference fields within a package, so that I can create name changes that cascade throughout it.

Potentially something like the following with the fieldRef type. We can reference in absolute. Or reference it via the kind and grab the index/name of the field in question.  

```yaml
apiVersion: 0.1.0
kind: Package
meta:
  pkgName:      pkg_name
  pkgVersion:   1
  description:  pack description
spec:
  resources:
    - kind: Label
      name: foo_label
    - kind: Bucket
      name:     foo_bucket
      associations:
       - kind: Label
         name: 
            fieldRef:
               key: spec.resources[0].name
    - kind: Dashboard
      name: foo_dash
     associations:
       - kind: Label
         name: 
            fieldRef:
               key: labels[0].name
```
