### ISSUE TITLE
Pkger should be compatible with a Kubernetes Object

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/influxdb#16501]
The manifest format is really close to be a K8s object but not quite there. 
at the top level these should be only four keys: `apiVersion`, `kind`, `metadata` and `spec`
- `apiVersion` right now is `0.1.0` but should be in the line of `influxdata.com/v1alpha1` https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/
- `kind` should be always formatted in a CamelCase format
- should be `metadata` and now it is `meta`

I don't understand why we have a super resource called Package

I imagine something going from this:
https://github.com/influxdata/influxdb/blob/master/pkger/testdata/variables.yml
```yaml
apiVersion: 0.1.0
kind: Package
meta:
  pkgName:      pkg_name
  pkgVersion:   1
  description:  pack description
spec:
  resources:
    - kind: Variable
      name: var_query_1
      description: var_query_1 desc
      type: query
      language: flux
      query: |
        buckets()  |> filter(fn: (r) => r.name !~ /^_/)  |> rename(columns: {name: "_value"})  |> keep(columns: ["_value"])
    - kind: Variable
      name: var_query_2
      description: var_query_2 desc
      type: query
      query: an influxql query of sorts
      language: influxql
    - kind: Variable
      name: var_const_3
      description: var_const_3 desc
      type: constant
      values:
        - first val
    - kind: Variable
      name: var_map_4
      description: var_map_4 desc
      type: map
      values:
        k1: v1
```

to something like

```yaml
apiVersion: influxdata.com/v1alpha1
kind: Variable
metadata:
  name: var_query_1
spec:
  description: var_query_1 desc
  type: query
  language: flux
  query: |
      buckets()  |> filter(fn: (r) => r.name !~ /^_/)  |> rename(columns: {name: "_value"})  |> keep(columns: ["_value"])
---
apiVersion: influxdata.com/v1alpha1
kind: Variable
metadata:
  name: var_query_2
spec:
  description: var_query_2 desc
  type: constant
  query: an influxql query of sorts
  language: influxql
---
apiVersion: influxdata.com/v1alpha1
kind: Variable
metadata:
  name: var_query_3
spec:
  description: var_query_3 desc
  type: constant
  values:
    - first val
---
apiVersion: influxdata.com/v1alpha1
kind: Variable
metadata:
  name: var_query_4
spec:
  description: var_query_4 desc
  type: map
  values:
    k1: v1
```

What do you think @jsteenb2? any thought @BondAnthony ?

Notes for deciding to add CRDs: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#should-i-add-a-custom-resource-to-my-kubernetes-cluster
