### ISSUE TITLE
Pkger resources are unique by name in pkg

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#17233]
We want to make all resource names in a pkg unique by name. We will allow users to change the user facing name/vanity name to be different from the resource name identifier.  Names are unique per resource type. The following is desired for enabling idempotency in support of gitops:

```yml
apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
  name: label_1 #vanity name defaults to label_1
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
  name: rucket_3 # is the reference name
spec:
  name: new vanity name # will be the vanity name
```

AC
- [ ] resources that provide a `spec.name` override the `metadata.name` field for the resource name
- [ ] when no `spec.name` provided, falls back to use the `metadata.name` field
- [ ] when exporting resources of the same name and type, the `metadata.name` will be appended by a suffix that makes it unique
