### ISSUE TITLE
Spike: Stack Ownership Model/Guardianship

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#17435]
Ideas thus far:

new resource mapping type:
   * entity mapping (Stack) as owner of resource
   * stack is owned by user similar (URM)

new role:
   * owner, member, pkger/stack?

**Comment by jsteenb2** [comment]
Can we turn guardianship on and off?

annotations define ownership

if you want to be able to delete it with the bucket, it is blocked by the owner of the stack.

Enhancing the templates to include

```yaml
kind: Bucket
metadata:
   name: foo-name
   forceDelete: always|when only reference(?)| never (default)
```
