### ISSUE TITLE
INFLUX_HOST variable has no effect on the behaviour of the `influx` utility

### ISSUE THREAD

**Issue by DavidAntliff** [influxdata/influxdb#17812]
I'm running influxdb-2.0.0-beta inside a Docker container. Therefore the database is accessed via `http://influxdb:9999` not `http://localhost:9999`.

As per the [docs](https://v2.docs.influxdata.com/v2.0/reference/cli/influx/#global-flags), the variable `INFLUX_HOST` should be available to set the default host for the `influx` command.

However the value of this environment variable seems to have no effect on the behaviour of the `influx` command.

__Steps to reproduce:__

`docker-compose.yml` (probably not the cause of this bug, but I include it for completeness):

```
version: '3'
services:
  telegraf:
    image: telegraf:1.14.1
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_UDP_ENABLED: "true"
    ports:
      - "9999:9999"
  influxdb-cli:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    entrypoint:
      - /bin/bash
    links:
      - influxdb
```

```$ docker-compose up -d```

```$ docker-compose run influxdb-cli```

```
root@abb28ed7c66b:/# INFLUX_HOST=http://influxdb:9999
root@abb28ed7c66b:/# export INFLUX_HOST
root@abb28ed7c66b:/# influx setup
Error: failed to determine if instance has been configured: Get http://localhost:9999/api/v2/setup: dial tcp 127.0.0.1:9999: connect: connection refused
See 'influx setup -h' for help
```

__Expected behavior:__

I would expect the value of `INFLUX_HOST` to be used when `influx setup` attempts to connect to the database, which would result in a successful connection attempt.

__Actual behavior:__

`influx setup` continues to use the default value `http://localhost:9999`, ignoring the value set by the `INFLUX_HOST` environment variable. The connection attempt fails because `localhost` is not the correct host name in this environment.

__Environment info:__
```
root@8524f9f092be:/# uname -srm
Linux 5.3.0-46-generic x86_64
```
```
root@8524f9f092be:/# influxd version
InfluxDB 2.0.0-beta.8 (git: 41a23242ea) build_date: 2020-04-21T05:01:12Z
```
```
$ docker --version
Docker version 18.09.7, build 2d0083d
```
Note that setting `INFLUX_HOST` in `docker-compose.yml` (which makes it set by default in the bash shell from which `influx` is run) also has no effect on the behaviour of `influx`.

Note also that specifying the host directly as `influx --host=http://influxdb:9999` does operate correctly.
