### ISSUE TITLE
Flux editor indicates errors when creating a newline (in toolsus1)

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#18965]
#### Background
The flux editor is throwing red squiggly complainy lines any time you do anything:

![dowhat.gif](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/3e3b73ae-17c6-4210-9af8-42a208756814)

![Screen Shot 2020-07-15 at 8.49.54 AM.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/1ab9e336-c402-4ba4-a005-66eaa0602a93)

#### Steps to Reproduce
1. load any query in the script editor
1. add a newline

**Comment by rickspencer3** [comment]
![Screen Shot 2020-07-29 at 1 47 13 PM](https://user-images.githubusercontent.com/13948193/88834580-124a7c80-d1a2-11ea-849b-3eb388581f86.png)

A tiny reproducer on tools

**Comment by yzhang1991** [comment]
I reviewed the entire workflow to generate those "squiggly lines":
* FluxMonacoEditor registers `onChange` handler:
https://github.com/influxdata/influxdb/blob/master/ui/src/shared/components/FluxMonacoEditor.tsx#L115
* The `onChange` handler:
https://github.com/influxdata/influxdb/blob/master/ui/src/shared/components/FluxMonacoEditor.tsx#L98
* We call `lspServer.current.didChange(docURI, text)` and send a `'textDocument/didChange'` request with the new content:
https://github.com/influxdata/influxdb/blob/master/ui/src/external/monaco.flux.messages.ts#L69
* This request is handled in LSP:
https://github.com/influxdata/flux-lsp/blob/master/src/handlers/document_change.rs#L36
* We cache the new version of the text then create diagnostics from it in the LSP:
https://github.com/influxdata/flux-lsp/blob/master/src/shared/mod.rs#L56
It basically creates AST from the text and runs AST checks on it. The errors are turned into the "Diagnostics" and returned back.
* After the diagnostics are returned, we call `updateDiagnostics()` which updates the Monaco editor's model markers:
https://github.com/influxdata/influxdb/blob/master/ui/src/shared/components/FluxMonacoEditor.tsx#L49
That becomes the squiggly lines.
Model marker: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imarker.html#source

So far, the problem described in this issue can only be observed in the tools cluster. Local OSS instances and production don't have this problem.
When you see those squiggly lines showing up, type `monaco.editor.getModelMarkers({})` in Chrome's console you will be able to see all the model markers.
On our tools cluster, no matter what you type in, there are always three errors showed in the model markers:
```
0:
    code: "1"
    endColumn: 2
    endLineNumber: 72
    message: "expected comma in property list, got SUB"
    owner: "default"
    relatedInformation: undefined
    resource: t {scheme: "inmemory", authority: "model", path: "/1", query: "", fragment: "", …}
    severity: 8
    source: undefined
    startColumn: 12
    startLineNumber: 1
    tags: undefined
1:
    code: "1"
    endColumn: 2
    endLineNumber: 72
    message: "cannot mix implicit and explicit properties"
    owner: "default"
    relatedInformation: undefined
    resource: t {scheme: "inmemory", authority: "model", path: "/1", query: "", fragment: "", …}
    severity: 8
    source: undefined
    startColumn: 12
    startLineNumber: 1
    tags: undefined
2:
    code: "1"
    endColumn: 27
    endLineNumber: 62
    message: "unexpected token for property key: SUB (-)"
    owner: "default"
    relatedInformation: undefined
    resource: t {scheme: "inmemory", authority: "model", path: "/1", query: "", fragment: "", …}
    severity: 8
    source: undefined
    startColumn: 6
    startLineNumber: 62
    tags: undefined
```
In my test cases, I only typed in a simple identifier `a`, but based on the error message, it is parsing a file with at least 72 lines which is impossible, and it always finds an error encountering a `SUB` token (`-`).

Because the errors we are seeing are uncorrelated to the content typed into the editor at all, and the problem happens in the tools cluster only, I think this is related to some prelude content that we send to LSP that is unique on the tools cluster.
https://github.com/influxdata/influxdb/blob/master/ui/src/external/monaco.flux.server.ts#L273
The prelude contains all the system and custom variables, therefore there must be something wrong with the variables defined in the tool cluster.

In checking all the variables defined in the tool cluster, I found this one variable whose name may cause a problem: `phil-unique tasks per`. After I changed it to `phil_unique_tasks_per`, the query editor in the tool cluster becomes normal again.

Take-away:
The UI/application team should implement a guard for the variable name input. Users should not be able to name a variable with "-", or spaces, it should be a valid identifier.
