### ISSUE TITLE
Set a default retention policy using env variables and docker

### ISSUE THREAD

**Issue by hadim** [influxdata/influxdb#19261]
Is that possible to set a default retention policy on the db created with the `INFLUXDB_DB` env variable with docker?

Here is my `docker-compose.yml` file:

```yaml
  grafana-db:
    container_name: grafana-db
    image: influxdb:1.7-alpine
    volumes:
      - my_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=my_db
      - INFLUXDB_USER=my_user
      - INFLUXDB_USER_PASSWORD=my_password
    restart: unless-stopped
    user: "1000"
```

That would be nice to be able to do that without having to write a custom init script and so a `Dockerfile` only for this.
