### ISSUE TITLE
wire GoReleaser with nfpm to generate and publish .deb and .rpm packages.

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#19473]
Need to update Goreleaser configuration file:
```
nfpms:
  - id: "influxdata"
    builds: ["influx", "influxd"]
    formats:
      - deb
      - rpm
```

**Comment by gshif** [comment]
I've been testing `nfpms` section of the goreleaser configuration file using my branch - `gs-build-test` and using s separate config file as well - `.goreleaser_gershon.yml`. So far the following config is working:
```
nfpms:
  -
    id: "influxdata"
    builds: ["influx", "influxd"]
    formats:
      - deb
      - rpm
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "influxdb-{{ .Version }}.{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
      deb:
        file_name_template: "influxdb_{{ .Version }}_{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
    vendor: InfluxData
    homepage: https://influxdata.com
    maintainer: support@influxdb.com
    description: Distributed time-series database.
    license: Proprietary
```

The name(s) of the produced `rpm` and `deb` packages, defined by the `file_name_template` variable, should resemble the names of the rpm and deb packages from influxDB 1.x (see https://github.com/influxdata/influxdb/issues/19321)
Building `influxd` arm v5 (armel) and arm v6 (armhf) is failing (see https://github.com/influxdata/influxdb/issues/19371)

**Comment by gshif** [comment]
Comparing with 1.x contents of rpm packages looks like a bunch of files needs to be created and added:
```
└─ $ ▶ rpm2cpio influxdb-1.8.2.arm64.rpm | cpio -idmv
./etc/influxdb/influxdb.conf
./etc/logrotate.d/influxdb
./usr/bin/influx
./usr/bin/influx_inspect
./usr/bin/influx_stress
./usr/bin/influx_tsm
./usr/bin/influxd
./usr/lib/influxdb/scripts/influxdb.service
./usr/lib/influxdb/scripts/init.sh
./usr/share/man/man1/influx.1.gz
./usr/share/man/man1/influx_inspect.1.gz
./usr/share/man/man1/influx_stress.1.gz
./usr/share/man/man1/influx_tsm.1.gz
./usr/share/man/man1/influxd-backup.1.gz
./usr/share/man/man1/influxd-config.1.gz
./usr/share/man/man1/influxd-restore.1.gz
./usr/share/man/man1/influxd-run.1.gz
./usr/share/man/man1/influxd-version.1.gz
./usr/share/man/man1/influxd.1.gz
./var/lib/influxdb
./var/log/influxdb
```

**Comment by gshif** [comment]
https://github.com/influxdata/build-scripts/tree/master/builds/templates/rpm/scripts

**Comment by gshif** [comment]
need to create a `scripts` directory in `influxdb` and add contents of https://github.com/influxdata/build-scripts/tree/master/builds/templates/rpm/scripts there

**Comment by gshif** [comment]
After updating goreleaser.yml nfpms section with:
```
nfpms:
  -
    id: "influxdata"
    builds: ["influx", "influxd"]
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        files:
          "scripts/init.sh": "/usr/lib/influxdb/scripts/init.sh"
          "scripts/influxdb.service": "/usr/lib/influxdb/scripts/influxdb.service"
          "scripts/logrotate": "/etc/logrotate.d/influxdb"
        scripts:
          preinstall:  "scripts/pre-install.sh"
          postinstall: "scripts/post-install.sh"
          postremove: "scripts/post-uninstall.sh"
        replacements:
          amd64: x86_64
        file_name_template: "influxdb-{{ .Version }}.{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
      deb:
        file_name_template: "influxdb_{{ .Version }}_{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
    vendor: InfluxData
    homepage: https://influxdata.com
    maintainer: support@influxdb.com
    description: Distributed time-series database.
    license: Proprietary
```

I launch RedHat instance : `Red Hat Enterprise Linux release 8.2 (Ootpa)` x86_64:
```
[root@ip-172-31-14-95 tmp]# rpm -qlp influxdb-9.9.9.x86_64.rpm 
/etc/logrotate.d/influxdb
/usr/bin/influx
/usr/bin/influxd
/usr/lib/influxdb/scripts/influxdb.service
/usr/lib/influxdb/scripts/init.sh
[root@ip-172-31-14-95 tmp]# rpm -ivh influxdb-9.9.9.x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:influxdb-0:9.9.9-1               ################################# [100%]
Created symlink /etc/systemd/system/influxd.service → /usr/lib/systemd/system/influxdb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/influxdb.service → /usr/lib/systemd/system/influxdb.service.
```
