### ISSUE TITLE
InfluxDB 2.0.0-rc. Delete not implemented

### ISSUE THREAD

**Issue by jmcomby** [influxdata/influxdb#19842]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Download the lastest rc version. docker-compose.yml
```
version: '2'

services:
  influxdb2:
    image: quay.io/influxdb/influxdb:2.0.0-rc
    restart: always
    container_name: influxdb2
    ports:
      - 8086:8086
    volumes:
      - /mnt/data/influxdb2:/root/.influxdbv2
    command :
       --reporting-disabled
```
2. Create a bucket and add data
3. Run bash: `docker exec -it influxdb /bin/bash`
4. Try to delete: `influx delete -o my-org --bucket my-bucket -t token --start '1970-01-01T00:00:00.00Z' --stop '2020-10-27T13:01:00.43Z'`

__Expected behavior:__
No error (Working on influxdb 2.0 beta)

__Actual behavior:__
Error: Failed to delete data: Not implemented.
See 'influx delete -h' for help

__Environment info:__

* System info: Linux 5.4.0-52-generic x86_64
* InfluxDB version: InfluxDB 2.0.0-rc.2 (git: 79c0b9bc4a) build_date: 2020-10-21T23:47:58Z
* Other relevant environment details: Docker version 19.03.13, build 4484c46d9d

__Config:__
Default config from docker image.
