### ISSUE TITLE
tls-strict-ciphers causes https service failure

### ISSUE THREAD

**Issue by Codecasaurus** [influxdata/influxdb#20762]
__Steps to reproduce:__
1. Set configuration (I did via yml config file) of "tls-strict-ciphers" to true along with other required tls options (cert/key)
2. Run influxdb container

__Expected behavior:__
InfluxDB should start successfully and be available via https using only the strict cipher suite. (ref: https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#tls-strict-ciphers)

__Actual behavior:__
https service fails to launch with log error noted below.
Without tls-strict-ciphers set to true, system starts successfully.

__Environment info:__
* System info: Podman on Fedora 33 Server x86_64
* InfluxDB version: InfluxDB 2.0.4 (git: 4e7a59bb9a) build_date: 2021-02-08T17:47:02Z (quay.io/influxdb/influxdb:v2.0.4)
* Other relevant environment details: All other configuration options standard.

__Config:__
```yml
tls-cert: /root/.influxdbv2/ssl/domain/fullchain.pem
tls-key: /root/.influxdbv2/ssl/domain/privkey.pem
tls-min-version: "1.2"
tls-strict-ciphers: true
```

__Logs:__
`lvl=error msg="Failed https service" log_id=0SMyA_Dl000 error="http2: TLSConfig.CipherSuites is missing an HTTP/2-required AES_128_GCM_SHA256 cipher (need at least one of TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 or TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256)."`
