### ISSUE TITLE
Regarding the influx multiple urls 

### ISSUE THREAD

**Issue by krishna710942** [influxdata/influxdb#21687]
hi all i have 3 connection urls of the influx how do i use in a uri string format . because i didnt get any example for that 

spring configuration -
```
spring:
  influxdb:
    gzip: true
    url: http://influx-influxdb.db.svc.cluster.local:8086
    username: test
    password: 123
    database: analytic
    retention-policy: autogen

```
but i wanted to implement this url in the influx urls ::

`influx-influxdb-0.influx-influxdb-headless.db.svc.cluster.local:8086,influx-influxdb-1.influx-influxdb-headless.db.svc.cluster.local:8086,influx-influxdb-2.influx-influxdb-headless.db.svc.cluster.local:8086`

how can i implement this url in the influx db .

code for the connection making

```
Builder client = new OkHttpClient.Builder();
      connection = InfluxDBFactory
        .connect(properties.getUrl(), properties.getUsername(), properties.getPassword(), client);
```

please help me in this.
