### ISSUE TITLE
influx export --endpoint-names requires organisation but not influx export --endpoints

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/influxdb#22494]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. `influx config create --active -n myOrg -u http://localhost:8086 -t <TOKEN>  -o myOrg`
2. `influx export --endpoint-names slack-xxx` fails
3. `influx export --endpoints id` works

__Expected behavior:__

First command should output endpoint configuration

__Actual behavior:__

```
influx export  --endpoint-names slack-xxx 
Error: Failed to clone resource: resource_id= resource_kind=NotificationEndpoint err="cloning resource: cannot process a request without a org or user filter".
```

whereas:

```
influx export  --endpoints <endpoint id>
apiVersion: influxdata.com/v2alpha1
kind: NotificationEndpointSlack
metadata:
    name: mystifying-ellis-fb6001
spec:
    name: slack-xxx
    status: active
    url: https://hooks.slack.com/services/<REDACTED>
```

__Environment info:__

* System info: Debian 10.10 / Linux 4.19.0-17-cloud-amd64 x86_64
* InfluxDB version: InfluxDB 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z
* Other relevant environment details: Using go binaries (no deb package)
