### ISSUE TITLE
Environment variable INFLUX_SKIP_VERIFY doesn't work

### ISSUE THREAD

**Issue by Forbzy** [influxdata/influxdb#22610]
**Which chart**:
Influxdb 
Chart Version: 2.3.11
App Version: 2.0.9

**Describe the bug**
The environment variable `INFLUX_SKIP_VERIFY` has no effect on the influx commands so my pod fails when it tries to run the `influx setup` commands. I have enabled TLS via the below snippet in the `values.yaml`. I've already tried setting the value to `"true"` and `""`.

```      
    extraEnvVars:
        - name: INFLUXD_TLS_CERT
          value: "/bitnami/influxdb/certs/tls.crt"
        - name: INFLUXD_TLS_KEY
          value: "/bitnami/influxdb/certs/tls.key"
        - name: INFLUX_HOST
          value: "https://localhost:8086"
        - name: INFLUX_SKIP_VERIFY
```

The documentation shows there is no default value for the variable. How do I assign it?
`https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/setup/`

**Expected behavior**
The influx commands should acknowledge the `INFLUX_SKIP_VERIFY` variable. It should work the same way it would if I used the flag `--skip-verify` for the CLI.

**Version of Helm and Kubernetes**:
Kubernetes v1.21.4
Docker Desktop 4.0.1
Docker Engine 20.10.8

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
