### ISSUE TITLE
Feature Flag "newAutoRefresh=false" does not work properly

### ISSUE THREAD

**Issue by darinfisher** [influxdata/influxdb#23143]
__Steps to reproduce:__

1. Start `influxd` with the feature flag
    `/usr/bin/influxd --feature-flags newAutoRefresh=false`
2. Login to the DB instance
3. Pull up a dashboard and look for the refresh dialog

__Expected behavior:__
The previous auto-refresh dialog should be available.

__Actual behavior:__
No auto-refresh dialog is available.

__Environment info:__

* System info: Linux 5.4.0-100-generic x86_64
* InfluxDB version: InfluxDB 2.1.1 (git: 657e1839de) build_date: 2021-11-09T03:03:48Z

__Config:__
```toml
bolt-path = "/data1/influxdb/influxd.bolt"
engine-path = "/data1/influxdb/engine"
http-bind-address = ":8086"
```

__Logs:__
NA

__Performance:__
NA
