### ISSUE TITLE
Upgrade from 2.4 to 2.5.1 fails

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/influxdb#23943]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run a docker container with the following configuration:
```
version: "3"
services:
  influx_source:
    image: influxdb:2.4
    volumes:
      - ./persist/:/var/lib/influxdb2
    ports:
      - 8086:8086
```
2. Upgrade the container to the following config
```
version: "3"
services:
  influx_source:
    image: influxdb:2.5.1
    volumes:
      - ./persist/:/var/lib/influxdb2
    ports:
      - 8086:8086
```
3. Influx will not become available due to a failed migration.

__Expected behavior:__
Influx is migrated to version 2.5

__Actual behavior:__
Migration fails and Influx does not boot again.

__Environment info:__

* System info: Linux 5.10.16.3-microsoft-standard-WSL2 x86_64
* InfluxDB version: 2.5.1

__Additional Info__
We have the same problem on a native Ubuntu 22.04 LTS machine. There, it does not run containerized but natively.

__Logs:__
```
ts=2022-11-23T11:54:36.665626Z lvl=info msg="Welcome to InfluxDB" log_id=0eL5Hby0000 version=v2.5.1 commit=5b6fdbf05d build_date=2022-11-02T18:06:28Z log_level=info
ts=2022-11-23T11:54:36.665701Z lvl=warn msg="nats-port argument is deprecated and unused" log_id=0eL5Hby0000
ts=2022-11-23T11:54:36.669581Z lvl=info msg="Resources opened" log_id=0eL5Hby0000 service=bolt path=/var/lib/influxdb2/influxd.bolt
ts=2022-11-23T11:54:36.670532Z lvl=info msg="Resources opened" log_id=0eL5Hby0000 service=sqlite path=/var/lib/influxdb2/influxd.sqlite
ts=2022-11-23T11:54:36.681797Z lvl=info msg="Backing up pre-migration metadata" log_id=0eL5Hby0000 service="SQL migrations" backup_path=/var/lib/influxdb2/influxd.sqlite.pre-v2.5.1-upgrade.backup
ts=2022-11-23T11:54:36.698400Z lvl=info msg="Bringing up metadata migrations" log_id=0eL5Hby0000 service="SQL migrations" migration_count=1
ts=2022-11-23T11:54:36.703379Z lvl=error msg="Failed to apply SQL migrations" log_id=0eL5Hby0000 error="FOREIGN KEY constraint failed"
```
