### ISSUE TITLE
The public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E

### ISSUE THREAD

**Issue by kenorb** [influxdata/influxdb#24090]
Ansible codebase which I'm using broke due to incorrect GPG key.

```
- name: Add InfluxData repository key (for Telegraf)
  become: true
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    id: 05CE15085FC09D18E99EFB22684A14CF2582E0C5
- name: Add InfluxData repository (for Telegraf)
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable
    mode: 0444
    update_cache: true
```

> `fatal: [bionic]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:GPG error: https://repos.influxdata.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E, E:The repository 'https://repos.influxdata.com/ubuntu bionic InRelease' is not signed."}`

What's the new public key to use? Where I can find it?

----

I've checked and the pubkey looks same (as above).

```
% gpg --with-fingerprint --show-keys <(wget -qO- https://repos.influxdata.com/influxdb.key)
pub   rsa4096 2015-09-28 [SC]
      05CE 1508 5FC0 9D18 E99E  FB22 684A 14CF 2582 E0C5
uid                      InfluxDB Packaging Service <support@influxdb.com>
sub   rsa4096 2015-09-28 [E]
```
