### ISSUE TITLE
INFLUXDB_COORDINATOR_WRITE_TIMEOUT not being taking into account in docker container

### ISSUE THREAD

**Issue by mikekuzak** [influxdata/influxdb#24102]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Docker compose:
```
  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
    ports:
      - 8054:8086
    volumes:
      - /data/influxdb/data:/var/lib/influxdb2
      - /data/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=xxxx
      - DOCKER_INFLUXDB_INIT_PASSWORD=xxxxx
      - DOCKER_INFLUXDB_INIT_ORG=myorg.com
      - DOCKER_INFLUXDB_INIT_BUCKET=HistoricalQuotesData
      - DOCKER_INFLUXDB_INIT_RETENTION=5d
      - INFLUXDB_COORDINATOR_WRITE_TIMEOUT=45s
    networks:
      - gateway
    labels:
      - traefik.enable=true
      - traefik.http.routers.influxdb.tls=true
```
2. login into container
3. run: influx server-config

__Expected behavior:__
"storage-write-timeout": 45000000000,

__Actual behavior:__
"storage-write-timeout": 10000000000,

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc
```
bash-5.1# uname -srm
Linux 5.15.79-flatcar x86_64

bash-5.1# influxd version
InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z
```

```
bash-5.1# set
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:expand_aliases:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=([0]="0")
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="1" [2]="16" [3]="1" [4]="release" [5]="x86_64-alpine-linux-musl")
BASH_VERSION='5.1.16(1)-release'
COLUMNS=174
DIRSTACK=()
DOCKER_INFLUXDB_COORDINATOR_WRITE_TIMEOUT=45s
DOCKER_INFLUXDB_INIT_BUCKET=HistoricalQuotesData
DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=default
DOCKER_INFLUXDB_INIT_MODE=setup
DOCKER_INFLUXDB_INIT_ORG=myorg.com
DOCKER_INFLUXDB_INIT_PASSWORD=xxxx
DOCKER_INFLUXDB_INIT_RETENTION=5d
DOCKER_INFLUXDB_INIT_USERNAME=xxxx
EUID=0
GROUPS=()
HISTFILE=/root/.bash_history
HISTFILESIZE=500
HISTSIZE=500
HOME=/root
HOSTNAME=656f3ad0bd67
HOSTTYPE=x86_64
IFS=$' \t\n'
INFLUXDB_COORDINATOR_WRITE_TIMEOUT=45s
INFLUXDB_VERSION=2.6.1
INFLUXD_INIT_PING_ATTEMPTS=600
INFLUXD_INIT_PORT=9999
INFLUX_CLI_VERSION=2.6.1
INFLUX_CONFIGS_PATH=/etc/influxdb2/influx-configs
LINES=30
MACHTYPE=x86_64-alpine-linux-musl
MAILCHECK=60
OPTERR=1
OPTIND=1
OSTYPE=linux-musl
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIPESTATUS=([0]="0")
PPID=0
PS1='\s-\v\$ '
PS2='> '
PS4='+ '
PWD=/
SHELL=/bin/ash
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
SHLVL=1
TERM=xterm
UID=0
_=version
```
