### ISSUE TITLE
Read initial database credentials from file for Docker Deployments

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/influxdb#24177]
__Proposal:__
Many container application support reading credentials from runtime mounted files (mainly achieved by the container runtime). Introduce following environment variables:

- `DOCKER_INFLUXDB_INIT_USERNAME_FILE`
- `DOCKER_INFLUXDB_INIT_PASSWORD_FILE`
- `DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE`

Values to these environment variables __WILL__ be full absolute paths to file where the credentials / secrets exist within the container filesystem.

This feature helps with the security aspect of not exposing initial credentials via environment variables set within the container when on performs snooping via container inspection:

```bash
docker inspect -f "{{ .Config.Env }}" <influxdb_container>
```

__Current behavior:__

Currently there is no such environment variables for either InfluxDBv1 / InfluxDBv2 and initialization always occurs through the defined environment variables:

- `DOCKER_INFLUXDB_INIT_USERNAME`
- `DOCKER_INFLUXDB_INIT_PASSWORD`
- `DOCKER_INFLUXDB_INIT_ADMIN_TOKEN`

__Desired behavior:__
Upon feature implementation:

- `DOCKER_INFLUXDB_INIT_USERNAME_FILE=/run/secrets/influx-admin-username`
- `DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influx-admin-password`
- `DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influx-admin-token`

with the following `docker-compose.yml` snippet:

```yml
services:
  influxdbv2:
    # snip
   environment:
    - DOCKER_INFLUXDB_INIT_USERNAME_FILE=/run/secrets/influx-admin-username
    - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influx-admin-password
   - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influx-admin-token
   secrets:
     - influx-admin-username
     - influx-admin-password
     - influx-admin-token
  # snip

secrets:
  influx-admin-username:
    environment: INFLUXDB_ADMIN_USER
  influx-admin-password:
    environment: INFLUXDB_ADMIN_PASSWORD
  influx-admin-token:
   environment: INFLUXDB_ADMIN_TOKEN
```

will bring up a docker container with influxdb configured by reading the contents of the respective secrets under `/run/secrets` directory mounted by docker.

__Use case:__
Why is this important (helps with prioritizing requests)?
Benefits to this approach will avoid displaying admin credentials either when doing `docker inspect` or `printenv` on the running container.

This approach is commonly used in other databases / applications like Grafana, MariabDB, MySQL, Portainer and this adds to a better and safer deployment strategy
