### ISSUE TITLE
Move data 2.4 influxdb server to 2.6 influxdb server

### ISSUE THREAD

**Issue by chi-miel** [influxdata/influxdb#24218]
Hello,

I migrate my data from a old server (influxdb 2.4) to a new (influxdb 2.6), it's work but influxdb almost all my memory.
 
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. install new server with influxdb 2.6
2. copy data from old server to new server
3. start new server

__Expected behavior:__
Working with same usage performance.

__Actual behavior:__
in the old server, Influxdb use les memory than in the new server.
old server had 6GB memory whereas the new serveur has 8 GB memory.
With de the new server, influx use ~7.5GB of memory. 

__Environment info:__
* System info: Linux 5.14.0-162.6.1.el9_1.x86_64 x86_64
* InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z
* Other relevant environment details: my server is a virtual machine and has a total disk 148GB with 63G used

__Config:__
add more time for start with /etc/systemd/system/influxdb.service.d/startup-timeout.conf :
```
[Service]
TimeoutStartSec=900
```
when i run influxd inspect report-tsm  --data-path /var/lib/influxdb/engine/data/  :
```
Summary:  Files: 1749
  Time Range: 1970-01-01T00:00:01.566216939Z - 2023-04-25T08:15:00Z
  Duration: 467336h14m58.433783061s

Statistics
  Series:
     - xxxxxxxxxxxxxxx (est): 124886 (7%)
     - xxxxxxxxxxxxxxx (est): 64 (0%)
     - xxxxxxxxxxxxxxx (est): 256 (0%)
     - xxxxxxxxxxxxxxx (est): 16132 (0%)
     - xxxxxxxxxxxxxxx (est): 495 (0%)
     - xxxxxxxxxxxxxxx (est): 3990 (0%)
     - xxxxxxxxxxxxxxx (est): 45 (0%)
     - xxxxxxxxxxxxxxx (est): 55 (0%)
     - xxxxxxxxxxxxxxx (est): 384 (0%)
     - xxxxxxxxxxxxxxx (est): 424056 (23%)
     - xxxxxxxxxxxxxxx (est): 1 (0%)
     - xxxxxxxxxxxxxxx (est): 407 (0%)
     - xxxxxxxxxxxxxxx (est): 1186490 (66%)
     - xxxxxxxxxxxxxxx (est): 546 (0%)
     - xxxxxxxxxxxxxxx (est): 323 (0%)
     - xxxxxxxxxxxxxxx (est): 4430 (0%)
     - xxxxxxxxxxxxxxx (est): 3306 (0%)
     - xxxxxxxxxxxxxxx (est): 13843 (0%)
  Total (est): 1773748
Completed in 3m45.958649935s
```
and this is output when i run  influx server-config :
```
{
        "assets-path": "",
        "bolt-path": "/var/lib/influxdb/influxd.bolt",
        "e2e-testing": false,
        "engine-path": "/var/lib/influxdb/engine",
        "feature-flags": null,
        "flux-log-enabled": false,
        "hardening-enabled": false,
        "http-bind-address": ":8086",
        "http-idle-timeout": 180000000000,
        "http-read-header-timeout": 10000000000,
        "http-read-timeout": 0,
        "http-write-timeout": 0,
        "influxql-max-select-buckets": 0,
        "influxql-max-select-point": 0,
        "influxql-max-select-series": 0,
        "instance-id": "",
        "log-level": "debug",
        "metrics-disabled": false,
        "nats-max-payload-bytes": 0,
        "nats-port": 0,
        "no-tasks": false,
        "pprof-disabled": false,
        "query-concurrency": 1024,
        "query-initial-memory-bytes": 0,
        "query-max-memory-bytes": 0,
        "query-memory-bytes": 0,
        "query-queue-size": 1024,
        "reporting-disabled": false,
        "secret-store": "bolt",
        "session-length": 60,
        "session-renew-disabled": false,
        "sqlite-path": "/var/lib/influxdb/influxd.sqlite",
        "storage-cache-max-memory-size": 1073741824,
        "storage-cache-snapshot-memory-size": 26214400,
        "storage-cache-snapshot-write-cold-duration": "10m0s",
        "storage-compact-full-write-cold-duration": "4h0m0s",
        "storage-compact-throughput-burst": 50331648,
        "storage-max-concurrent-compactions": 0,
        "storage-max-index-log-file-size": 1048576,
        "storage-no-validate-field-size": false,
        "storage-retention-check-interval": "30m0s",
        "storage-series-file-max-concurrent-snapshot-compactions": 0,
        "storage-series-id-set-cache-size": 100,
        "storage-shard-precreator-advance-period": "30m0s",
        "storage-shard-precreator-check-interval": "10m0s",
        "storage-tsm-use-madv-willneed": false,
        "storage-validate-keys": false,
        "storage-wal-fsync-delay": "0s",
        "storage-wal-max-concurrent-writes": 0,
        "storage-wal-max-write-delay": 600000000000,
        "storage-write-timeout": 10000000000,
        "store": "disk",
        "testing-always-allow-setup": false,
        "tls-cert": "",
        "tls-key": "",
        "tls-min-version": "1.2",
        "tls-strict-ciphers": false,
        "tracing-type": "",
        "ui-disabled": false,
        "vault-addr": "",
        "vault-cacert": "",
        "vault-capath": "",
        "vault-client-cert": "",
        "vault-client-key": "",
        "vault-client-timeout": 0,
        "vault-max-retries": 0,
        "vault-skip-verify": false,
        "vault-tls-server-name": "",
        "vault-token": ""
}
```

__Logs:__
Sometime i see events that take time : 
service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/engine/data/xxxxxxxxxxxxxxxx/autogen/6538 duration=1358.492ms

__Performance:__
influxdb system status show 2.8Gb usage but not with pmap : 
systemd
```
influxdb.service - InfluxDB is an open-source, distributed, time series database
     Loaded: loaded (/usr/lib/systemd/system/influxdb.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/influxdb.service.d
             └─startup-timeout.conf
     Active: active (running) since Tue 2023-04-04 10:54:10 CEST; 3 weeks 0 days ago
       Docs: https://docs.influxdata.com/influxdb/
   Main PID: 150779 (influxd)
      Tasks: 28 (limit: 48878)
     Memory: 2.8G
        CPU: 1d 11h 32min 17.229s
     CGroup: /system.slice/influxdb.service
             └─150779 /usr/bin/influxd
```
pmap
```
Address           Kbytes     RSS   Dirty Mode  Mapping
.....
total kB         53828476 2506748 2362612
```
i don't understand how the output (what is relevant etc)
```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"

i join the file iostat.txt
```
iostat -xd 1 30 > iostat.txt
[iostat.txt](https://github.com/influxdata/influxdb/files/11330016/iostat.txt)
```

Someone has some advice / analyse / help ? 

Thank
