### ISSUE TITLE
Unable to connect to Influx from a certain IP

### ISSUE THREAD

**Issue by SpiralCut** [influxdata/influxdb#24609]
Hi, I'm having trouble accessing InfluxDB 2.7.5 from a certain IP address on another subnet.  I'm running influx on a windows PC within a docker container inside of WSL, and I was previously successfully able to send data via telegraf from a sever on the 192.168.3.X subnet to the influx PC on the 192.168.1.X subnet in the past.  I had some hardware issues on the PC (which are now fixed) but after several crashes I no longer can

__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. .Telnet from the 192.168.3.3 server to the Influx DB server at 192.168.1.4

__Expected behaviour:__
I should see a connection handshake with the 192.168.1.4 server

__Actual behaviour:__
Describe What actually happened.
There will be no reaction from the InfluxDB server (I see the same result when i run telegraf but telnet makes it clearer that it isn't a telegraf config issue)

I'm finding it trouble to provide meaningful logs but so far what I've tried
1) Checking my router/network firewall etc.  Verified that the 192.168.3.3 server is making it through the firewall and if I change the port I try to telnet to I can successfully telnet into the windows server (though I can't telnet into Influx if I change the influx port and then try connecting to that0

2) Tried telneting from another computer on a different subnet (192.168.4.X) and from _that_ computer I was able to connect though still not from 192.168.3.3

3) Checked the windows computer. Tried re-adding firewall rules for influx (in this case on port 8087)  and disabling the firewall altogether but I'm still not able to connect from 192.168.3.3 (still can connect from other IPs though)

4) Viewed the connection in Wireshark on the windows PC.  I see the 192.168.3.3 server try to connect in the logs but it isn't making the connection and gives up after retrying a few times

5) Because of this, it seems to be exclusively an issue between this IP (192.168.3.3 and influx on the windows server)

__Environment info:__
192.168.1.4
Influx DB 2.7.5 running on WSL2 (Ubuntu 22.04 LTS) in a Docker Container.  WSL is hosted in Windows 11

InfluxDB Docker Compose Script
```

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8087:8086
    networks:
      - t2_proxy
    environment:
      - INFLUXD_STORAGE_CACHE_SNAPSHOT_MEMORY_SIZE=104857600
#      - INFLUXD_LOG_LEVEL=debug
      - INFLUXDB_MONITOR_STORE_ENABLED=false

```

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
["influx.conf"]
  url = "https://influx.MYDOMAIN.com"
  token = ""
  org = ""
# 
# [eu-central]
#   url = "https://eu-central-1-1.aws.cloud2.influxdata.com"
#   token = "XXX"
#   org = ""
# 
# [us-central]
#   url = "https://us-central1-1.gcp.cloud2.influxdata.com"
#   token = "XXX"
#   org = ""
# 
# [us-west]
#   url = "https://us-west-2-1.aws.cloud2.influxdata.com"
#   token = "XXX"
#   org = ""
