### ISSUE TITLE
Missing _monitoring system bucket

### ISSUE THREAD

**Issue by qdel** [influxdata/influxdb#24918]
__Steps to reproduce:__

```shell
$> influx bucket list
ID                      Name            Retention       Shard group duration    Organization ID         Schema Type
1f0b7f93eee31365        _tasks          72h0m0s         24h0m0s                 0fb9ddd02e0b86db        implicit
5ac999f5d8a9894a        batterystats    infinite        168h0m0s                0fb9ddd02e0b86db        implicit
23e6a8a6b5544aeb        default         168h0m0s        24h0m0s                 0fb9ddd02e0b86db        implicit
1e44de25ae87b286        docker          720h0m0s        24h0m0s                 0fb9ddd02e0b86db        implicit
84b910126dacae33        linky           infinite        168h0m0s                0fb9ddd02e0b86db        implicit
42c4db6643210999        nginx           720h0m0s        24h0m0s                 0fb9ddd02e0b86db        implicit
72c711e492786cd0        telegraf        2160h0m0s       24h0m0s                 0fb9ddd02e0b86db        implicit
f8241b0bbbb34483        telegraf_1m     infinite        168h0m0s                0fb9ddd02e0b86db        implicit
fbc48ead3cda9628        veolia          infinite        168h0m0s                0fb9ddd02e0b86db        implicit
```

__Expected behaviour:__
_monitoring should be present

__Actual behaviour:__
It is not

__Environment info:__

Very old instance, using influxdb v1. All data migration made.

__Config:__

Started using docker compose. But config is really simple:
```yaml
  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"
    volumes:
      - /opt/influxdb2:/var/lib/influxdb2
    #environment:
    #  - INFLUXD_LOG_LEVEL=error
    networks:
      - super
    restart: unless-stopped
    cpu_shares: 1800
```

__Logs:__

No relevant logs found.
