### ISSUE TITLE
aggregateWindow(every: 1mo, offset: -1s) calculates wrong dates for december

### ISSUE THREAD

**Issue by DaCookie4u** [influxdata/influxdb#26008]
__Steps to reproduce:__

1. Query data using `aggregateWindow(every: 1mo, offset: -1s)`
2. Look at the results

__Expected behaviour:__
I expect `_time` of each result to be the last second, of the last day of each month, i.e.: `2024-12-31T23:59:59.000Z`

Using `offset: -86401s` should return the last second of the day before the last day, i.e.: `2024-12-30T23:59:59.000Z`

__Actual behaviour:__
In december `_time` shows the last day to be the 30th for `offset: -1`: `2024-12-30T23:59:59.000Z`

Using `offset: -86401s` does not return the 29th, but the 30th again: `2024-12-30T23:59:59.000Z`

__Environment info:__

I am running InfluxDB in docker on an up-to-date arch linux host. I don't think this has anything to do with my machine, but here is the docker compose service section I am using to spin this up:

```
influxdb:
    image: 'influxdb:2'
    restart: always
    user: "1000:1000"
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=<redacted>
      - DOCKER_INFLUXDB_INIT_PASSWORD=<redacted>
      - DOCKER_INFLUXDB_INIT_ORG=<redacted>
      - DOCKER_INFLUXDB_INIT_BUCKET=<redacted>
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=<redacted>
    volumes:
      - /<redacted>/data:/var/lib/influxdb2
      - /<redacted>/conf:/etc/influxdb2
```
