### ISSUE TITLE
Duplicate Data Issue in InfluxDB2 Queries

### ISSUE THREAD

**Issue by Horjer** [influxdata/influxdb#26098]
#### **Issue Description**  
When querying data in InfluxDB2, we observed that **multiple records exist for the same timestamp**, even when they have identical **measurement, tag set, field key, and time** values.  

Restarting **InfluxDB2 does not resolve the issue**.  

Additionally, this issue **depends on the query time range**:  
- Some query time ranges return duplicate data.  
- Simply adjusting the time range may eliminate the duplicates.  

#### **Environment Information**  
- **InfluxDB Version**: 2.7.10  
- **Deployment Method**: Docker  
- **Docker Compose Configuration**:  
  ```yaml
  version: '3.5'

  services:
    influxdb:
      restart: always
      image: influxdb:2.7.10
      container_name: influxdb
      volumes:
        - ./config/config.yml:/etc/influxdb2/config.yml
        - ./data/influxdb:/var/lib/influxdb2
      ports:
        - 8086:8086
      environment:
        - INFLUXDB_HTTP_WRITE_BUFFER_SIZE=10000
        - INFLUXDB_HTTP_MAX_QUEUED_WRITE_LIMIT=100000
        - INFLUXDB_HTTP_WRITE_TIMEOUT=10s
        # - INFLUXDB_MAX_CONCURRENT_WRITES=100
  ```

---

#### **Steps to Reproduce**  

1. Run the following Flux query:  
   ```flux
   from(bucket: "vpp_test")
   |> range(start: 2025-03-01T13:19:00Z, stop: 2025-03-01T13:24:00Z)
   |> filter(fn: (r) => r.statistics_diff_minute_1 == "RS_2720057d000c3203_EPI")
   |> map(fn: (r) => ({ r with time_ns: uint(v: r._time) }))
   ```
   **Query Result (Contains Duplicates):**
   ```plaintext
   {_time=2025-03-01T13:20:00Z, _value=8.008, time_ns=1740835200000000000}
   {_time=2025-03-01T13:21:00Z, _value=8.489, time_ns=1740835260000000000}
   {_time=2025-03-01T13:22:00Z, _value=8.481, time_ns=1740835320000000000}
   {_time=2025-03-01T13:23:00Z, _value=8.489, time_ns=1740835380000000000}
   {_time=2025-03-01T13:20:00Z, _value=8.008, time_ns=1740835200000000000}  // Duplicate
   {_time=2025-03-01T13:21:00Z, _value=8.489, time_ns=1740835260000000000}  // Duplicate
   {_time=2025-03-01T13:22:00Z, _value=8.481, time_ns=1740835320000000000}  // Duplicate
   {_time=2025-03-01T13:23:00Z, _value=8.489, time_ns=1740835380000000000}  // Duplicate
   ```
   **InfluxDB UI Screenshots:**
  
![Image](https://github.com/user-attachments/assets/eda95d46-fba5-4975-94cf-c361359474f2)

2. **Modify the query time range** and execute the query again:  
   ```flux
   from(bucket: "vpp_test")
   |> range(start: 2025-03-01T13:20:00Z, stop: 2025-03-01T13:24:00Z)
   |> filter(fn: (r) => r.statistics_diff_minute_1 == "RS_2720057d000c3203_EPI")
   |> map(fn: (r) => ({ r with time_ns: uint(v: r._time) }))
   ```
   **Query Result (No Duplicates):**
   ```plaintext
   {_time=2025-03-01T13:20:00Z, _value=8.008, time_ns=1740835200000000000}
   {_time=2025-03-01T13:21:00Z, _value=8.489, time_ns=1740835260000000000}
   {_time=2025-03-01T13:22:00Z, _value=8.481, time_ns=1740835320000000000}
   {_time=2025-03-01T13:23:00Z, _value=8.489, time_ns=1740835380000000000}
   ```
   **InfluxDB UI Screenshots:**
  
![Image](https://github.com/user-attachments/assets/d66f1ab5-063f-447f-9c17-2fa064c2cfdc)

  

#### **Expected Behavior**  
According to InfluxDB2's data storage rules, duplicate records for the same timestamp should not exist. Queries **should not return duplicate data**.  

#### **Possible Causes**  
- **InfluxDB caching mechanism may be causing inconsistent query results**.  
- **Query optimizer bug** causing deduplication failure under certain time ranges.  
- **Indexing issues** leading to multiple retrievals of the same timestamped data.  

---

#### **Attempted Solutions**  
- **Restarted InfluxDB** → Issue persists.  
- **Adjusted query time range** → Some time ranges return duplicates, while others do not.  

---

#### **Help Needed**  
- Is this a known bug? Is there an official fix?  
- Are there any workarounds, such as clearing caches or modifying queries?  
- Any debugging guidance to further investigate the root cause?  

---
