### ISSUE TITLE
InfluxDB3 Core failed to initialized write buffer: error from wal: join error

### ISSUE THREAD

**Issue by yhj945** [influxdata/influxdb#26549]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Server abnormal power outage
2. Restart InfluxDB

__Expected behaviour:__
Start InfluxDB service normally.

__Actual behaviour:__
Unable to start InfluxDB service. Error: Serve command failed: failed to initialized write buffer: error from wal: join error: task 1276 panicked with message "range end index 8 out of range for slice of length 0"

__Environment info:__

System info: 
Linux 5.10.209-rt101 aarch64

docker-compose.yaml
```
influxdb3-core:
    image: influxdb:3.1.0-core
    container_name: influxdb3-core
    restart: always
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
	
      - --node-id=node0
      - --log-filter=debug
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
      - --max-http-request-size=20971520
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /app/data/influxdb3/data:/var/lib/influxdb3
```

__Logs:__
2025-06-20T06:20:39.219208Z  INFO influxdb3_wal::snapshot_tracker: timestamps passed in and wal file num min_time=Timestamp(1750345682239000000) max_time=Timestamp(1750345682239000000) wal_file_number=WalFileSequenceNumber(34053)
2025-06-20T06:20:39.219219Z  INFO influxdb3_wal::object_store: replaying WAL file n_ops=1 min_timestamp_ns=1750345682239000000 max_timestamp_ns=1750345682239000000 wal_file_number=34053 snapshot_details=None
2025-06-20T06:20:39.219689Z  INFO influxdb3_cache::parquet_cache: cache request handler closed
2025-06-20T06:20:39.219696Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
2025-06-20T06:20:39.219734Z  WARN executor: DedicatedExecutor dropped without waiting for worker termination
Serve command failed: failed to initialized write buffer: error from wal: join error: task 1276 panicked with message "range end index 8 out of range for slice of length 0"
