### ISSUE TITLE
influxdb doesn't start f the api port is commented out and the ssl port used instead

### ISSUE THREAD

**Issue by jvshahid** [influxdata/influxdb#367]
The following configuration will cause influxdb to die without any error messages:

``` toml
[api]
#port = 60500
ssl-port = 8086
ssl-cert = "cert.pem"
```
