### ISSUE TITLE
Dropping data node can create shard groups with no owners

### ISSUE THREAD

**Issue by ashb** [influxdata/influxdb#5680]
I had misconfigured my test cluster so that one of the data nodes was still bound to localhost:

```
> show servers                                                                                                                                                                                                                        [36/126]
name: data_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8086  172.17.0.1:8088
3       172.17.0.1:8086 172.17.0.1:8088
```

So I ran `drop data server 1` (which I found out from #5583 - it's not documented anywhere yet but there's already a ticket to improve those docs) and then on both the meta servers I saw:

> [monitor] 2016/02/13 17:32:52 failed to store statistics: write failed
> [monitor] 2016/02/13 17:33:02 failed to store statistics: write failed
> [monitor] 2016/02/13 17:33:12 failed to store statistics: write failed

This repeated until i stopped the servers, removed the /var/lib/influxdb/meta folder on both and restarted them (just restarting the servers didn't help.)

Influx 0.10.0 form deb package, unedited config file, had set INFLUXDB_META_HTTP_BIND_ADDRESS and INFLUXDB_META_BIND_ADDRESS environment variables but not INFLUXDB_HTTP_BIND_ADDRESS -- setting that properly fixed it.

**Comment by e-dard** [comment]
@ashb was `localhost` also running a meta node? And if so, did you drop that too?

**Comment by ashb** [comment]
@e-dard no, the meta ndoes were correctly configured to use the IP addresses.

I'll get repro steps tonight.

**Comment by ashb** [comment]
Here you go @e-dard. docker-compose-based as it's easy to isolate and reproduce.


Commands to run:

```bash
docker-compose up # File is below

# In a different terminal run this
docker-compose run --rm influx3 influx --host influx1 --execute 'show servers'
docker-compose run --rm influx3 influx --host influx1 --execute 'drop data server 3' #  Check the id in previous command
```

docker-compose.yml:

```yaml
influx1:
  container_name: influx1
  image: tutum/influxdb:0.10
  command: ["bash", "-c", "INFLUXDB_HTTP_BIND_ADDRESS=$$(hostname -i):8086 INFLUXDB_META_BIND_ADDRESS=$$(hostname -i):8088 INFLUXDB_META_HTTP_BIND_ADDRESS=$$(hostname -i):8091 exec influxd"]

influx2:
  container_name: influx2
  image: tutum/influxdb:0.10
  links:
    - influx1
  command: ["bash", "-c", "INFLUXDB_META_BIND_ADDRESS=$$(hostname -i):8088 INFLUXDB_META_HTTP_BIND_ADDRESS=$$(hostname -i):8091 exec influxd -join influx1:8091"]

influx3:
  container_name: influx3
  image: tutum/influxdb:0.10
  links:
    - influx1
    - influx2
  command: ["bash", "-c", "INFLUXDB_META_BIND_ADDRESS=$$(hostname -i):8088 INFLUXDB_META_HTTP_BIND_ADDRESS=$$(hostname -i):8091 exec influxd -join influx1:8091 -join influx2:8091"]
```
A few seconds after running the drop node command all three servers in this example start complaining with the same error.
