### ISSUE TITLE
Pre-creating database with influxdb

### ISSUE THREAD

**Issue by anarwal27** [influxdata/influxdb#8537]
I am running influxdb with docker-compose and has been working perfectly, however now I want to precreate database with docker-compose file. I tried providing env variable to do so, but does not seem to work. Is there something wrong in the way I am doing it?

```
version: '2'
services:

#Install latest influxdb docker image from docker-hub: https://hub.docker.com/_/influxdb/
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
      - "8083:8083"
      - "8090:8090"
      - "8099:8099"
    environment:
      INFLUXDB_DATA_ENGINE: tsm1
      PRE_CREATE_DB: "smash-db"
```
