### ISSUE TITLE
Influxdata Ubuntu repository Issue

### ISSUE THREAD

**Issue by abednarik** [influxdata/influxdb#9199]
### Bug report

Starting today while trying to add Influxdata Ubuntu repository we get a SSL issue

__Steps to reproduce:__

In our case we use SaltStack to automate this tasks. This is the relevant code we use and was working for long time without issues

```yml
influxdata_repo:
  pkgrepo.managed:
    - humanname: Influxdata repo
    - name: {{ telegraf.pkg_repo }}
    - key_url: https://repos.influxdata.com/influxdb.key
    - file: /etc/apt/sources.list.d/influxdata.list
    - require_in:
      - pkg: telegraf
```
**telegraf.pkg_repo**: _deb https://repos.influxdata.com/ubuntu trusty stable_ 

__Expected behavior:__ 

Repository is added without issues

__Actual behavior:__ 

We get a redirect to plain http
```
$ wget -S -O /dev/null  https://repos.influxdata.com/ubuntu
--2017-12-05 10:52:02--  https://repos.influxdata.com/ubuntu
Resolving repos.influxdata.com... 54.192.227.58, 54.192.227.5, 54.192.227.201, ...
Connecting to repos.influxdata.com|54.192.227.58|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 301 Moved Permanently
  Content-Type: text/html; charset=iso-8859-1
  Content-Length: 345
  Connection: keep-alive
  Date: Tue, 05 Dec 2017 12:38:16 GMT
  Server: Apache/2.4.18 (Ubuntu)
  Location: http://repos-backend.influxdata.com/ubuntu/
  Age: 4428
  X-Cache: Hit from cloudfront
  Via: 1.1 8a5a428bf0f67e7e942f8f1010a97910.cloudfront.net (CloudFront)
  X-Amz-Cf-Id: SfMo0E63RK2LiETDW8fSJ5GNdU35l8J_6fXh1ZU2QLGi2MvgbJ1KgQ==
Location: http://repos-backend.influxdata.com/ubuntu/ [following]
--2017-12-05 10:52:02--  http://repos-backend.influxdata.com/ubuntu/
Resolving repos-backend.influxdata.com... 54.193.78.188
Connecting to repos-backend.influxdata.com|54.193.78.188|:80... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Date: Tue, 05 Dec 2017 13:52:05 GMT
  Server: Apache/2.4.18 (Ubuntu)
  Vary: Accept-Encoding
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Content-Type: text/html;charset=UTF-8
Length: unspecified [text/html]
Saving to: '/dev/null'

/dev/null                                               [ <=>                                                                                                                ]   1.95K  --.-KB/s    in 0s

2017-12-05 10:52:03 (27.2 MB/s) - '/dev/null' saved [2000]
```

And an error in Salt

```yml
       ----------
                 ID: influxdata_repo
           Function: pkgrepo.managed
               Name: deb https://repos.influxdata.com/ubuntu trusty stable
             Result: False
            Comment: Failed to configure repo 'deb https://repos.influxdata.com/ubuntu trusty stable': [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
            Started: 04:48:37.358615
           Duration: 136.58
```

Thanks
